### ISSUE TITLE
Index and expose original filename

### ISSUE THREAD

**Issue by theefer** [guardian/grid#1004]
We resisted it for a while but talking to users it's actually necessary to retain the original filename of the uploaded file in the image metadata. The reason is that often people receive images, and then later on more instructions or descriptions for these images, and the only way to relate the two is the filename. Currently the filename isn't kept or shown anywhere.

**Question: what to do if an image is re-uploaded?**
I suggest we override with the new filename if provided, and keep the previous one if not.

**Comment by paperboyo** [comment]
:gem:
Yes, I can provide plenty of use cases. Including convoluted ones, like having to sort by filename even after _downloading_ images from Grid to make an animated GIF when frames were originally uploaded to Grid (I know that the above issue does not cater for this example - but goes a long way at least!). Thanks for not resisting any more ;-)

**Comment by alastairjardine** [comment]
>We resisted it for a while but talking to users it's actually necessary to retain the original filename of the uploaded file in the image metadata.

What was the logic/rationale for resisting?

**Comment by theefer** [comment]
The main requirement for filenames at the time came from Getty (for rights purposes) and we agreed with them it was not sensible because files get downloaded, renamed, etc, and relying on filename as a reference between systems is not a good idea.

Here the idea is more to use it as a reference for humans, specifically to the person who uploaded the files and holds these files, and it seems to make more sense in that context.

**Comment by alastairjardine** [comment]
@theefer Thanks – context helps.

**Comment by jamesgorrie** [comment]
> and keep the previous one if not

How can we not supply a filename?

**Comment by theefer** [comment]
We're just posting data to the upload endpoint, I don't think we currently send any filename at all? I might be wrong.

**Comment by jamesgorrie** [comment]
Ah yes - we don't.
