### ISSUE TITLE
Add delete button to toolbar on picture grid page

### ISSUE THREAD

**Issue by akash1810** [guardian/grid#1041]
_From @alastairjardine on August 6, 2015 9:57_

We have a toolbar, we should use it!

_Copied from original issue: guardian/grid-infra#107_

**Comment by akash1810** [comment]
Any ideas on the UX on this when multiple images are selected, as currently:
- anyone can delete their own uploads
- the ability to delete any image is permission based

What'll happen when your selection includes an image that you're not allowed to delete for whatever reason?

**Comment by akash1810** [comment]
I was thinking of having adding the delete action to the hover items. Good/bad?

**Comment by akash1810** [comment]
_From @alastairjardine on August 6, 2015 10:6_

Perhaps enable only for the people who have the permission in the first instance.

**Comment by akash1810** [comment]
_From @theefer on August 6, 2015 10:7_

> I was thinking of having adding the delete action to the hover items. Good/bad?

It's such a rare action, seems unwarranted noise?

**Comment by akash1810** [comment]
btw, wrong repo?

**Comment by akash1810** [comment]
_From @alastairjardine on August 6, 2015 10:15_

@akash1810 Probably :(

**Comment by akash1810** [comment]
_From @alastairjardine on August 6, 2015 10:16_

@akash1810 I would try to keep the image functions to the most frequently used.

**Comment by akash1810** [comment]
> It's such a rare action, seems unwarranted noise?

and

>  I would try to keep the image functions to the most frequently used.

Slightly related - presumably this also goes for a download button? i.e. the download button goes to the toolbar.

**Comment by theefer** [comment]
I would have said so.

**Comment by alastairjardine** [comment]
> Slightly related - presumably this also goes for a download button? i.e. the download button goes to the toolbar. 

Yep, _especially_ as you might want to download a multiple image selection

**Comment by kenoir** [comment]
> Any ideas on the UX on this when multiple images are selected

Actions that cannot be performed on the full batch result in a disabled button.

If you're looking for actions to go in the toolbar, i'd try the archiver as it's probably pretty straightforward to implement and a reasonably common action.

**Comment by akash1810** [comment]
Any pointers on the behaviour of the search results? My current thinking is the thumbnail should disappear but the placeholder square should remain (until reload).

**Comment by alastairjardine** [comment]
Sounds good. Perhaps ghost in a trashed symbol to make it super clear
that's what happened?

On Friday, 14 August 2015, Akash A <notifications@github.com> wrote:

> Any pointers on the behaviour of the search results? My current thinking
> is the thumbnail should disappear but the placeholder square should remain
> (until reload).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/issues/1041#issuecomment-131108846>.
>


-- 
--
Alastair Jardine, Senior UX Architect

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by kenoir** [comment]
Step towards this: https://github.com/guardian/grid/pull/1110

**Comment by akash1810** [comment]
Fixed in https://github.com/guardian/grid/pull/1101 via the monstrosity that is https://github.com/guardian/grid/pull/1153 :disappointed:
