### ISSUE TITLE
Typing / in search query gets substituted to %2F

### ISSUE THREAD

**Issue by theefer** [guardian/grid#1059]
Some weird URL-encoding loop going on here between the query and the URL. Strangely only occurs for `/` and no other URL-encoded character (e.g. `?` or `&`).

Steps to reproduce:
1. Type `/` in search input

Expected:
2. `/` stays in search input, URL contains `?query=%2F`

Actual:
2. search inputs gets re-written to `%2F` and URL contains `?query=%252F`

**Comment by akash1810** [comment]
Related PR https://github.com/angular-ui/ui-router/pull/2071
