### ISSUE TITLE
Guardian Repos

### ISSUE THREAD

**Issue by dkelbley** [guardian/grid#1077]
In the NGINX configuration, it states to 4.Get the dev-nginx repo checked out on your machine and 
5.Set up certs if you've not already done so.  However, I get a 404 error when attempting to connect.  Do you have any suggestions on how I can workaround this issue?

**Comment by theefer** [comment]
You're right, that repo is currently private. It doesn't contain anything secret or special though, it's just used to help setup the configuration and SSL certs for a local nginx server that binds the expected ports to the expected domain names. In other words, you should be able to get Grid running without dev-nginx.

However I agree it'd be easier with it, and the README should not reference closed repos, so I will see what we can do to open that repo up, thanks for flagging up!

**Comment by dkelbley** [comment]
Thank you for getting back with me so quickly!  It's good to know I can still get the project up and running without the Guardian repos.
