### ISSUE TITLE
Grid Configuration

### ISSUE THREAD

**Issue by dkelbley** [guardian/grid#1081]
In the settings_dev.py, where do I obtain values for the following properties?

PROPERTIES = {
    'domain_root': <PRIVATE_VALUE>,
    'mixpanel_token': <PRIVATE_VALUE>,
    'panda_domain': <PRIVATE_VALUE>,
    'panda_aws_key': <PRIVATE_VALUE>,
    'panda_aws_secret': <PRIVATE_VALUE>,
    'cors': <PRIVATE_VALUE>,
}

**Comment by dkelbley** [comment]
Also, in the NGINX configuration section on line 6, where do I obtain /setup-app.rb and /nginx-mapping.yml?

**Comment by kenoir** [comment]
A bit related to the comment @theefer makes here: https://github.com/guardian/grid/issues/1077 `nginx-mapping.yml` is part of our Guardian specific setup so not available here.

This project relies on https://github.com/guardian/pan-domain-authentication where the `panda_` values are consumed. That project should be enlightening as to where to get the values from.

**Comment by dkelbley** [comment]
Ok, new issue with Kahuna.  When I run setup.sh, I get the following error message:

Installing NPM dependencies
Installing JSPM packages
/usr/bin/env: node: No such file or directory
##teamcity[message text='jspm install error' status='ERROR']

Any thoughts on how to resolve this issue?

**Comment by theefer** [comment]
Do you have node installed and available on your `$PATH`?

**Comment by dkelbley** [comment]
Good call!  I had to create symlink for node based on nodejs.  Now, I'm running into the following problem:

**Comment by dkelbley** [comment]
# sbt
[info] Set current project to kahuna (in build file:/home/ubuntu/guardian/grid/kahuna/)
> project kahuna
[info] Set current project to kahuna (in build file:/home/ubuntu/guardian/grid/kahuna/)
> run 9005
[info] Updating {file:/home/ubuntu/guardian/grid/kahuna/}kahuna...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 1 s, completed Aug 17, 2015 7:06:38 PM

Any thoughts on this one?

**Comment by theefer** [comment]
Make sure you start `sbt` from the root, not from within the `kahuna` directory.

**Comment by dkelbley** [comment]
Thanks for the help!  I'm finally able to load each module.  However, when I try to access any of the modules from a web browser, i.e. http://<location>:9001, I receive the following:

org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
     org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:273)
     org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:192)
     org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient.execute(InternalTransportClusterAdminClient.java:81)
     org.elasticsearch.client.support.AbstractClusterAdminClient.state(AbstractClusterAdminClient.java:138)
     org.elasticsearch.action.admin.cluster.state.ClusterStateRequestBuilder.doExecute(ClusterStateRequestBuilder.java:94)
     org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
     org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
     com.gu.mediaservice.lib.elasticsearch.ElasticSearchClient$class.getCurrentAlias(ElasticSearchClient.scala:67)
     lib.elasticsearch.ElasticSearch$.getCurrentAlias(ElasticSearch.scala:51)
     com.gu.mediaservice.lib.elasticsearch.ElasticSearchClient$class.ensureAliasAssigned(ElasticSearchClient.scala:37)
     lib.elasticsearch.ElasticSearch$.ensureAliasAssigned(ElasticSearch.scala:51)
     Global$.beforeStart(Global.scala:15)

Can you please point me in the right direction on this error?

**Comment by theefer** [comment]
Are you sure you are running elasticsearch?

**Comment by dkelbley** [comment]
Good catch!  I forgot about restarting Elasticsearch.  Ok, here's my next issue:
play.api.UnexpectedException: Unexpected exception[ExceptionInInitializerError: null]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:170) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
Caused by: java.lang.ExceptionInInitializerError: null
        at Global$.onStart(Global.scala:19) ~[na:na]
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
        at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.6.jar:na]
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: CCE2CD77E7EBA997)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1078) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3735) ~[aws-java-sdk-s3-1.9.24.jar:na]

I noticed the media-server-DEV user was missing permissions to the S3 buckets.  I went ahead and assigned the user access.  However, I also noticed the buckets are empty.  Is this normal?  And, am I missing something else as the app still won't load?

**Comment by theefer** [comment]
I assume you're trying to startup media-api?

It might be worth trying to push an empty `permissions.properties` files to your config bucket just to silence a known error if missing.

However Global.scala line 19 seems to be the keybucket. Can you check you have the correct `aws.id` and `aws.secret` in `/etc/gu/media-api.properties`? Can you list the contents of the keybucket using these credentials?

**Comment by theefer** [comment]
And is `auth.keystore.bucket` also pointing to the correct bucket?  e.g. `auth.keystore.bucket=media-service-dev-foobar-keybucket-32kld9230`

**Comment by dkelbley** [comment]
Correct, I'm able to start media-api fine.  However, when I attempt to connect remotely, this is when the error message appears.  I'm able to perform an "aws s3 ls" and see all of the buckets.  However, all of my buckets are empty.  Is this normal?  The aws.id and aws.secret is correct in the /etc/gu/media-api.properties files as I used these same credentials for "aws configure".  Also, where should I define auth.keystore.bucket?

**Comment by theefer** [comment]
`auth.keystore.bucket` should be in `/etc/gu/media-api.properties` too. Did you use the dot-properties helper in the scripts directory to generate your properties files? (It's just a helper script, you can also do them by hand)

**Comment by theefer** [comment]
It's fine for the buckets to be empty, as by default there are no keys or permissions.

**Comment by dkelbley** [comment]
Somehow, I overlooked the auth.keystore.bucket in media-api.properties.  It is defined as auth.keystore.bucket=media-server-dev-test-keybucket-104n5gh4pqz2d and it matches the S3 bucket name.  I tested the S3 bucket permissions by copying a file into s3://media-server-dev-test-keybucket-104n5gh4pqz2d and it worked fine.  Any suggestions on getting media-api running from a web browser?  I receive the following error message on the browser

ExceptionInInitializerError: null


No source available, here is the exception stack trace: 

->java.lang.ExceptionInInitializerError: 
     Global$.onStart(Global.scala:19)
     play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
     play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
     scala.collection.immutable.List.foreach(List.scala:381)
     play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.utils.Threads$.withContextClassLoader(Threads.scala:21)
     play.api.Play$.start(Play.scala:90)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
     scala.Option.map(Option.scala:146)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
     scala.util.Success.flatMap(Try.scala:230)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
     scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
     scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
     scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
     scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
     scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107

And on the console:

! @6n749o095 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[ExceptionInInitializerError: null]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:170) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
Caused by: java.lang.ExceptionInInitializerError: null
        at Global$.onStart(Global.scala:19) ~[na:na]
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
        at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.6.jar:na]
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 4DF8CD4FD47EF60F)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1078) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296) ~[aws-java-sdk-core-1.9.24.jar:na]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3735) ~[aws-java-sdk-s3-1.9.24.jar:na]

**Comment by akash1810** [comment]
Are you sure `/etc/gu/media-api.properties` has the correct credentials? Your stack trace shows an `AmazonS3Exception` being thrown.

`aws.id` and `aws.secret` should be the values from your cloudformation output.

You can use the aws cli to double check these values (assuming you have [jq](https://stedolan.github.io/jq/)):

```sh
aws cloudformation describe-stacks --stack-name <STACK_NAME> \
| jq -c '.Stacks[0].Outputs[] | select(.OutputKey | contains("AwsId", "AwsSecret"))'
```

As @theefer suggested:

> It might be worth trying to push an empty permissions.properties files to your config bucket just to silence a known error if missing.

**Comment by dkelbley** [comment]
Thank you for the aws cloudformation syntax and jq command, it was very handy!  Although I verified the AwsId and AwsSecret credentials are correct, the app still refused to load.  I also created an empty file called permissions.properties and placed it in the media-server-dev-wieck-configbucket-i14yyqbxvlam.  It made no difference.  The only valid which isn't defined in the media-api.properties file is cors.allowed.origins.  I wasn't sure how to obtain this value.  Any further suggestions?

**Comment by kenoir** [comment]
`cors.allowed.origins` in `media-api.properties` needs a comma separated list of origins for CORS requests. The only essential one I would guess is that of `kahuna`, this is something like: `https://kahuna.internal.url`.

**Comment by dkelbley** [comment]
Thanks for the information!  I updated the media-api.properties file with the kahuna entry.  However, I'm still having problems overcoming the ExceptionInInitializerError: null error.  I tried assigning the media-server-DEV-test-User-MKSXUC2TO4JO to the administrators group and it didn't make any difference.  As such, it appears I still have a configuration issue somewhere.  My media-api.properties file is below:

domain.root=guardian.test.com
aws.id=<AWS>
aws.secret=<AWS Secret>
s3.image.bucket=media-server-dev-test-imagebucket-1ju4iexxpth37
s3.thumb.bucket=media-server-dev-test-thumbbucket-dofds3cx7g22
auth.keystore.bucket=media-server-dev-test-keybucket-104n5gh4pqz2d
sns.topic.arn=arn:aws:sns:us-east-1:821587675737:media-server-DEV-test-Topic-1WNVRWKVX3LIC
cors.allowed.origins=https://kahuna.internal.url
s3.config.bucket=media-server-dev-test-configbucket-i14yyqbxvlam
persistence.identifier=picdarUrn

Do you see anything which appears wrong?  Also, if it's helpful, I'm not able to load any of the other projects either from a web browser.  Same error message.

Note:  For security purposes, I excluded the credentials associated with aws.id and aws.secret.  The domain root has also been changed but is similar to the format listed above.

**Comment by akash1810** [comment]
Hi, apologies that its proving difficult to get set up. Could you run `sbt clean` from the project root to remove any artefacts. Then `sbt "project media-api" "run 9001"` from the project root to start `media-api`.

**Comment by akash1810** [comment]
Your `media-api.properties` looks fine to me too.

**Comment by theefer** [comment]
Could you provide the full stack trace for your latest error? I wonder if it could be the Panda setup actually.

**Comment by dkelbley** [comment]
I truly appreciate all of your help!!!!  I received the same rror message after running sbt clean followed by project media-api with run 9001.  What is the best way to provide a full stack trace?  Also, I'm sure you're right, it's probably due to my Panda setup...since I was guessing on that one.  Is there any information I can provide on it which would be helpful?

**Comment by theefer** [comment]
So I assume you have a `/etc/gu/panda.properties` file with valid AWS credentials (`panda.aws.key` and `panda.aws.secret`) as well as a `panda.domain` set?

If so, you need to check that these credentials allow you to read (get) to a file named `<domain>.settings` (where `<domain>` is the same as your `panda.domain` property) within an S3 bucket named `pan-domain-auth-settings`. IOW you should be able to retrieve the file with:

`AWS_ACCESS_KEY_ID=<panda.aws.key> AWS_SECRET_ACCESS_KEY=<panda.aws.secret> aws s3 cp s3://pan-domain-auth-settings/<panda.domain>.settings .`
(if you have the `aws` python CLI)

If so, this file should hold the correct configuration [as described in the pan-domain repo](https://github.com/guardian/pan-domain-authentication/#setting-up-your-domain-configuration). Some of these settings like the 2fa group seem somewhat Guardian specific, so we could try and make them optional if they are an issue with external people trying to use the library.

Hopefully this will help.

**Comment by dkelbley** [comment]
This is a huge help!  Ok, in my panda.properties file I have the following elements defined:
panda.domain=guardian.test.com
panda.aws.key=<awskey>
panda.aws.secret=<awssecret>

However, I was guessing on the panda.domain so this may be some of the confusion.  I assigned it a standard hostname such as guardian.test.com.  I was really confused in the panda setup.  So, here is my question...do I need to create an S3 bucket named s3://pan-guardian.test.com-auth-settings?  And then create a file called guardian.test.com.settings with the panda information?  I'm asking specifically about the bucket name as I realize bucket names must be UNIQUE.  As or the panda information, are all of the fields required?

publicKey=example_key
privateKey=example_key
cookieName=exampleAuth

googleAuthClientId=example_google_client
googleAuthSecret=example_google_secret

googleServiceAccountId=serviceAccount@developer.gserviceaccount.com
googleServiceAccountCert=name_of_cert_in_bucket.p12
google2faUser=an.admin@example.com
multifactorGroupId=group@2fa_admin_user

I'm not sure where I should get any of this information.  Doyou have any recommendations?  or instance, is it enough to simply create an IAM user with multifactor authentication or use the one previously created?  And where do I get the public/private keys and cookieName?

Thanks!

**Comment by theefer** [comment]
The bucket name is static, `pan-domain-auth-settings`. Only the filename changes, `guardian.test.com.settings` in your case.

I suggest refering to the pan-domain repo for more on its configuration and the source to check for required fields: https://github.com/guardian/pan-domain-authentication/

**Comment by gordonclarkok** [comment]
Hi,
I was experiencing the same issue, but had to modify the following to add my own unique bucket:
<pre>object PublicSettings {
  val bucketName = "<b>pan-domain-auth-settings-foo</b>"
  val cookieName = "gutoolsAuth"
  val assymCookieName = s"$cookieName-assym"
</pre>

This can be found in the following file from the pan-domain-authentication repo:
<pre>~/pan-domain-authentication/pan-domain-auth-verification/src/main/scala/com/gu/pandomainauth/PublicSettings.scala</pre>

Then do an sbt clean/package & modify the snapshot to the newly built artefact in:
<pre>~/grid/project/Dependencies.scala</pre>

Then sbt package this.

At the moment I'm now getting:
<pre>
play.api.UnexpectedException: Unexpected exception[ExceptionInInitializerError: null]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:170) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
Caused by: java.lang.ExceptionInInitializerError: null
	at Global$.onStart(Global.scala:19) ~[na:na]
	at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.6.jar:na]
Caused by: java.util.NoSuchElementException: key not found: secret
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractMap.default(Map.scala:59) ~[scala-library-2.11.6.jar:na]
	at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[scala-library-2.11.6.jar:na]
	at scala.collection.AbstractMap.apply(Map.scala:59) ~[scala-library-2.11.6.jar:na]
	at com.gu.pandomainauth.model.PanDomainAuthSettings$.apply(PanDomainAuthSettings.scala:46) ~[pan-domain-auth-core_2.11.jar:0.2.8-SNAPSHOT]
</pre>
Which I presume is down to not having the correct entries in <pre>mydomain.settings</pre> in the bucket.

Hope this helps,
Regards,
Gordon

**Comment by BogdanNicolau** [comment]
Hi,

The bucket name is indeed hardcoded and needs to be changed as specified in the previous comment. An sbt publishLocal  followed by modifying the dependencies will quickly fix this hurdle. The mydomain.settings file that needs to be uploaded to the above bucket must also contain a key called "secret" which is the shared secret used to sign the cookie.

**Comment by ivanrigovsky** [comment]
Hi,
I have same problem. I change bucket and now have only one message in log:
"DEBUG GUUID= application:74 - user not authed against <my domain>, return 401
How to debug it, and which user must to be authed?

**Comment by mrsn** [comment]
Hello together,
I am also having some troubles with panda:  "user not authed against foo.bar, return 401" but I am not getting the redirect to google at all. Do i need some special config in the keystore.bucket ? Can you also give an example of how a permissions.properties should look like. Thanks for the nice project and greetings.

**Comment by kbossee** [comment]
Those 401's after completing the panda setup are probably the same I was getting, see https://github.com/guardian/grid/issues/1381

**Comment by m-sanders** [comment]
I have managed to get it all running locally and have added my 'notes' to a Gist in case it helps anyone else: https://gist.github.com/m-sanders/081b9b3d0b4a6a210485

I do still have permissions issues where I have had to grant the user created by cloudFoundation additional permissions (Current Admin - Yikes!) to run the media-service.

**Comment by akash1810** [comment]
> I do still have permissions issues where I have had to grant the user created by cloudFoundation additional permissions (currently admin - Yikes!) to run the media-service.

@m-sanders what are the additional perms you've added? Which service was failing without them?

**Comment by m-sanders** [comment]
@akash1810 I have not investigated this issue yet and stuck with admin perms. I am a complete noob with AWS and as I have just been setting up Grid as a demo, I have not sunk the time into investigating them as it isn't a blocker for my demo. If I get some time in the next week or so, I'll have another look and create a ticket.

**Comment by akash1810** [comment]
Quite a late response... #2927 looks like it'll help here. Would be interested to get your feedback on it.
