### ISSUE TITLE
Isolation of graphicsmagick and libgd

### ISSUE THREAD

**Issue by nathanaeljones** [guardian/grid#1083]
Given the intrinsic difficulty of ever making imagemagick or graphicsmagick secure, how can it be isolated from the rest of the application ? 

Would it be possible to isolate it in a unprivileged docker container? It seems the existing micro-service division might lend easily to this kind of solution.

**Comment by kenoir** [comment]
We use restrictions on inbound ports to all the services when running in AWS.

**Comment by kenoir** [comment]
Closing as I don't think this is something we'll address as part of this project.
