### ISSUE TITLE
link to dev-nginx is broken

### ISSUE THREAD

**Issue by mingfang** [guardian/grid#1090]
I'm getting 404 here https://github.com/guardian/dev-nginx

**Comment by akash1810** [comment]
Hi, we've been made aware of this here https://github.com/guardian/grid/issues/1077, more specifically, @theefer 's [comment](https://github.com/guardian/grid/issues/1077#issuecomment-130363247). We're working on fixing this.

**Comment by nvercamm** [comment]
Hello,

can we get this repo from somewhere? I'm trying to setup your grid system

**Comment by TravelTrexIT** [comment]
Hi Guys, we are hanging with our test installation of grid. Can you estimate when the dev Link will be available again?

**Comment by theefer** [comment]
The dev-nginx script is really just a helper to install SSL certificates and setup a local nginx config. You should be able to run all the services without it, on ports 9001-9008 and, if needed, configure a local http server to serve these different localhost ports over different virtual host domains?

**Comment by TravelTrexIT** [comment]
we are actaully missing the setup-app.rb script to perform step 6 command of the nginx setup. 
"sudo /setup-app.rb /nginx-mapping.yml" 
I thought that might be in dev-nginx. Can you give me a hint where to find it?

**Comment by theefer** [comment]
I'll be looking into open sourcing the dev-nginx repo. That said, as mentioned above, it's really just a helper that writes some nginx virtual-host config files for all the domains described in the `nginx-mapping.yml` file, with some local SSL certificates, e.g. `https://api.media.local.domain.com/` => `http://localhost:9001/`. You should be able to set these up even without dev-nginx if you want to run the service now.

Sorry for the inconvenience.

**Comment by kbossee** [comment]
nginx-mapping.yml wasn't very clear for me, I had to look at Services.scala to really get how the urls are composed.

Suppose your domain is "example.com", and you choose the most obvious name for the app: grid.

Then the urls become:
```
kahuna            grid.example.com
media-api         api.grid.example.com
image-loader      loader.grid.example.com
cropper           cropper.grid.example.com
metadata-editor   grid-metadata.example.com
imgops            grid-imgops.example.com
grid-usage        grid-usage.example.com
```

With these urls, you should have in your settings.ini
```
domain_root = grid.example.com
panda_domain = example.com
```

There are some checks in the code that require https.
If you need to create an ssl-certificate, I followed [this tutorial](http://articles.slicehost.com/2007/12/19/ubuntu-gutsy-self-signed-ssl-certificates-and-nginx)

Your ngnix.config should contain a server config for each of the urls, like so:
```
  server {
    listen               443;
    ssl                  on;
    ssl_certificate      /etc/ssl/certs/myssl.crt;
    ssl_certificate_key  /etc/ssl/private/myssl.key;
    keepalive_timeout    70;
    server_name grid.example.com;
    location / {
      proxy_pass  http://localhost:9005;
    }
  }
```
I added each of those urls to my host file, but probably it'll work fine if you simply add
```127.0.0.1       grid.example.com```


If you're using a self signed certificate as in the tutorial, it's not a trusted certificate though.
So if you go to https://grid.example.com you'll get a security warning and you have to manually accept the certificate.
I had to manually accept the certificate for each of those urls.
The cropper makes a call to media-api, so it'll also have problems with the untrusted certificate.
The easy (and dirty) way to get around this is by adding "ws.acceptAnyCertificate=true" to application.conf

Hope this helps.

**Comment by akash1810** [comment]
Fixed in https://github.com/guardian/grid/pull/1586.
