### ISSUE TITLE
panda when installing grid

### ISSUE THREAD

**Issue by stevepiki** [guardian/grid#1103]
Hello, I'm trying to install grid and having trouble with panda.
I realized that to run grid APIs, I have to use pan domain authentication.

Is PRIVATE_VALUE in dot_properties can be  given or do I need to make my own panda system ?

**Comment by akash1810** [comment]
> Is PRIVATE_VALUE in dot_properties can be given or do I need to make my own panda system ?

The latter. This should help - https://github.com/guardian/pan-domain-authentication.

**Comment by stevepiki** [comment]
Thank you for your answer!

**Comment by theefer** [comment]
Closing, let us know if still an issue.

**Comment by akash1810** [comment]
Quite a late response... #2927 looks like it'll help here. Would be interested to get your feedback on it.
