### ISSUE TITLE
No extension for ZIPs in Chrome on Windows 8.1 and 10 [was: Download toolbar button]

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#1123]
Hello,

Just testing new download button on search page (in browser). I would expect it to create a ZIP file **only** if more than one image is selected, otherwise it should work exactly as the download button on an image page (in viewer). Currently, it looks like it creates a ZIP file regardless, even for just one JPG file which means more work for me and for the computer. It says no.

Also, in Chrome 45.0.2454.46 beta-m (64-bit) on Win 10, the ZIP files have no extension, so that OS can’t deal with them at all and the user must append the ZIP extension manually.

Also, the button does not work **at all** for me in Firefox 41.0b2 (same OS). Console says:

```
Object { data: ArrayBuffer, status: 403, headers: xt/<(), config: Object, statusText: "Forbidden" } undefined build.js:3:24231
i/<() build.js:3
mt/this.$get</<() build.js:3
.execute/</</<() build.js:29
u() build.js:3
c/<() build.js:3
gn/this.$get</p.prototype.$eval() build.js:4
gn/this.$get</p.prototype.$digest() build.js:4
gn/this.$get</p.prototype.$apply() build.js:4
o() build.js:3
v() build.js:3
Ct/</_.onload()
```

Otherwise - great!

Regards
Mateusz

**Comment by akash1810** [comment]
the 403 error suggests the token to get the file from s3 expired - a refresh *should* fix that, though the token to access the image should be refreshed silently so you wouldn't have to do so.

**Comment by paperboyo** [comment]
Oops, my bad. Interface seemed fully functional - just the button did nothing on press. Of course it works in FF now, sorry. And the ZIP file has an extension there.

While minor, I think other problems are still valid:

 - [ ] unnecessary creation of ZIPs for just one file

- [ ] no extension for ZIPs in Chrome

- [ ] naming ZIPs and files as per https://github.com/guardian/grid/pull/1080#issuecomment-130676450 and other comments there

Feel free to close if too minor or known, thanks.

**Comment by akash1810** [comment]
> unnecessary creation of ZIPs for just one file

fixed in https://github.com/guardian/grid/pull/1125.

**Comment by paperboyo** [comment]
Thx, @akash1810! Leaving it open, but feel free to close whenever you feel like.

**Comment by akash1810** [comment]
will close when all items in list are checked :) ... need to get a copy of windows 10 to reproduce the no extension problem, though.

**Comment by paperboyo** [comment]
> need to get a copy of windows 10 to reproduce the no extension problem

I assumed it's all Chromes everywhere. Assumed wrongly. After testing just now, Chrome on Mac and Chrome on Win XP are fine. Chrome 43, 32-bit on Win 8.1  (near dotcom) joins the weirdos party with Chrome 44, 64-bit on my home Win 10. Strangest thing! Not worth more than max 3,5m of debugging, IMHO, since nobody uses Windows anyway. But the best few. One. Me.
