### ISSUE TITLE
Can't make image valid with no editing rights

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#1141]
If an image is missing a credit or description (invalid) the user is prompted to add the missing info.
If the user does not have the permissions to, they cannot.

Not sure what the solution is - but it's definitely a problem.

![invalid-error](https://cloud.githubusercontent.com/assets/31692/9464241/4b82b148-4b1a-11e5-8d2c-74c9bbb5e043.png)

**Comment by paperboyo** [comment]
+1. Happened to me several times. But also, I would have fixed many images with wrong metadata, would I have permissions. Emailing every single one to the power user seem more annoying that even I can bear. I wonder if there are more people like me vs. those who are looking to sneakily introduce errors into our perfect db ;-)

There is one solution to that: give permissions to all :open_hands: (maybe log changes and give revert ability for those concerned).

**Comment by kenoir** [comment]
Works as designed :(
