### ISSUE TITLE
dot-properties readme not clear for people outside of the guardian

### ISSUE THREAD

**Issue by bogguard** [guardian/grid#1211]
At the dot-properties [readme](https://github.com/guardian/grid/tree/master/scripts/dot-properties) the [properties] attributes are saying the following : 
*all values within the properties section can be given to you by a member of The Grid development team.*

As i'm not a member of The Guardian development team I'm unable to fill those in or request them. 
Empty property values makes it unable to run the different projects.

**Comment by akash1810** [comment]
Sorry about that, will make it more descriptive soon. Are there any values in particular you are not certain about?

**Comment by bogguard** [comment]
Hi akash1810, currently i have no clue what to fill in on those properties :
domain_root =
mixpanel_token =
cors =
panda_domain =
panda_aws_key =
panda_aws_secret =
sqs_message_min_frequency =

**Comment by akash1810** [comment]
@bogguard comments added to file now - sorry for the delay!
