### ISSUE TITLE
Support live bloggers: shouldn't have to repeatedly enter Usage Rights & Credit

### ISSUE THREAD

**Issue by rtyley** [guardian/grid#1287]
@cb372 , @mchv and I have been [live-blogging Scala World 2015](https://www.theguardian.com/info/developer-blog/live/2015/sep/21/conference-report-scala-world-2015), taking random photos with our phones as we go along, and inserting them via the Grid into the liveblog.

Once the physical upload has taken place, there's some boilerplate we have to repeatedly enter each time, ie. we need to re-enter Usage Rights, Description & Credit - though only one of those should be essential. We shouldn't have to re-enter Usage Rights & Credit each time - especially because setting the Usage Rights currently takes 5 clicks+manually typing our own name in as an 'Other' photographer:

![optimised](https://cloud.githubusercontent.com/assets/52038/10017064/695210c8-6123-11e5-82e4-7255d0d2db13.gif)

**Comment by jamesgorrie** [comment]
See: #1283

**Comment by theefer** [comment]
Batch applying usage rights (which is on the board) would also help in the case you are uploading multiple images at once and want to apply the same usage rights to all.

If uploaded separately, you could already use the selection in the search results (when showing just your uploads) to batch edit rights and metadata. One thing that could be nice there is, when rights/metadata differ between images in your selection, to suggest using any of the values from images in your selection for your whole selection. Not urgent but a nice-to-have.

**Comment by paperboyo** [comment]
Some cameras let's you edit Copyright metadata. Also, more than just some include serial no. of your specific camera in the metadata... Maybe that info could become useful somehow (for a limited number of known users, obv.)?

**Comment by theefer** [comment]
@paperboyo Not sure what you mean? The copyright field should already be visible on the image preview page and editable (if present) there and on the upload page.

**Comment by paperboyo** [comment]
Filling out/suggesting specific metadata/UR templates based on these EXIF fields. Future, future.

**Comment by theefer** [comment]
Ah, we could do that fairly easily if photographers do that, although we're currently asking them to fill in the photographer field instead.

**Comment by paperboyo** [comment]
Inferring meta from image meta could also help with some uploaders/emailers and could be, maybe, useful to some teams: here is a droplet, Sir, just drag this thing that you work on every day/week onto it. Maybe.

**Comment by jamesgorrie** [comment]
We're looking at asking illustrators to their metadata in photoshop and then mapping automatically when we ingest their image - we could do something similar so long as we know what metadata the camera is filling in.

**Comment by theefer** [comment]
We've added the ability to batch set usage rights on upload, and it's possible from the search results too.
