### ISSUE TITLE
Docker-compose / Kubernetes

### ISSUE THREAD

**Issue by lucmichalski** [guardian/grid#1308]
Hi guys,

Thanks for this great repo, is there any Kubernetes deployment files or Docker-compose to test this framework ?

Have a good week end all !

**Comment by theefer** [comment]
We don't have any yet, but that'd be really interesting to help make it easier to build and deploy. Contributions welcome!

**Comment by EdgeCaseBerg** [comment]
:+1: would love to see an easy way to boot this up with docker

**Comment by lucmichalski** [comment]
I see much more crane or kubernetes to deploy such framework. As soon as I finish a couple of stuff, I will check that out.

Also, I would see an extension with Neo4J of Grid:
https://github.com/kbastani/spark-neo4j/blob/master/app/docker-compose.yml

**Comment by akash1810** [comment]
Fixed in https://github.com/guardian/grid/pull/1586.
