### ISSUE TITLE
Match photographers even if byline is truncated

### ISSUE THREAD

**Issue by theefer** [guardian/grid#1325]
e.g. 38e4b6756d0c13014a35f35f760a42042627658a has "Christopher Thomond for The Gua" due to the limit in length of 32 chars for the byline field. Other of his pictures have an untruncated longer by-line, so the truncation is probably due to an app rewriting the metadata before we get the file.

1. Can we get the full untruncated data from somewhere, as hinted by @paperboyo elsewhere? A quick exiftool dump of the metadata doesn't show the full version in any other field unfortunately.
2. Can we detect truncated for the GU bylines optimistically?

**Comment by paperboyo** [comment]
Ad. 1. Not in these new pics (I've checked one of them only). They have ALL the fields truncated :(

**Comment by theefer** [comment]
Yes, so we should make the logic work for those. I'm on it.
