### ISSUE TITLE
Pan Domain Authentication Problem

### ISSUE THREAD

**Issue by mmmaaaxxx77** [guardian/grid#1404]
I get 『Service: Amazon S3; Status Code: 403; Error Code: AccessDenied;』when I run the media-api.
I think the error is the panda.aws.key/secret in 『/etc/gu/panda.properties』not correct.
How can I get the panda.aws.key/secret ?
I cannot understand how to get it from https://github.com/guardian/pan-domain-authentication...

**Comment by jamesgorrie** [comment]
hi @mmmaaaxxx77 - have you set the panda properties up yet?
Given that it's a 403, you might be using our (not yet configurable) domain that [we hardcode in the PandaAuth](https://github.com/guardian/grid/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/auth/Panda.scala#L14)?

**Comment by mmmaaaxxx77** [comment]
to @jamesgorrie :
my panda.properties:
panda.domain=udn.com
panda.aws.key={My.IAMUser.AwsId}
panda.aws.secret={My.IAMUser.AwsSecret}

I think the panda.aws.key/secret are wrong, but I don't understand how to get it.

**Comment by jamesgorrie** [comment]
Have you setup the `udn.settings` file in the `pan-domain-auth-settings` for that IAM user?

The other thing to make sure is that the [domain in the `PanDomainAuthActions`](https://github.com/guardian/grid/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/auth/Panda.scala#L14) is set to your Google domain and that that domain is setup correctly.

**Comment by mmmaaaxxx77** [comment]
a stupid question...
How can I setup settings file in the pan-domain-auth-settings bucket?

**Comment by jamesgorrie** [comment]
[There's a pretty thorough run through on the pan-domain repo](https://github.com/guardian/pan-domain-authentication#setting-up-your-domain-configuration)

**Comment by mmmaaaxxx77** [comment]
How upload the setting file to pan-domain-auth-settings bucket?
Is pan-domain-auth-settings's awsId/Secret necessary? how to get it?

**Comment by jamesgorrie** [comment]
You will need to create a bucket in your own AWS account then upload the settings there.
The id/secret will be for an account that can access this.

This is currently the only way as we don't have a non-authenticated version.

**Comment by mmmaaaxxx77** [comment]
When I create bucket which name is 『pan-domain-auth-settings』, S3 show the 『The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.』 message. It looks like I can't create 『pan-domain-auth-settings』 bucket in my S3. Is it normal?

**Comment by theefer** [comment]
We've just released a new patch version that lets you configure the bucket name using an environment variable (https://github.com/guardian/pan-domain-authentication/pull/20). Can you try it and see if that solves your issue?

Thanks

**Comment by theefer** [comment]
Oops, we'd screwed up the release and it hadn't gone out, sorry. It's publishing now.

Closing as hopefully this solves this issue.

**Comment by akash1810** [comment]
Quite a late response... #2927 looks like it'll help here. Would be interested to get your feedback on it.
