### ISSUE TITLE
No results when search for unquoted byline

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#1422]
When searching for a full name of a photographer in the byline, no results are surfaced, except when quotes are used in the search.

Query: `/search?query=Charles%20Emerson`

Expected - To show results
Current - Shows no results, unless you quote the name (`/search?query="Charles%20Emerson"`)

**Comment by NickPapacostas** [comment]
fixed on prod as of https://github.com/guardian/grid/pull/1744
