### ISSUE TITLE
ElasticsearchException[Missing mandatory plugins [cloud-aws]]

### ISSUE THREAD

**Issue by husrevo** [guardian/grid#1431]
Hi,

When I try to setup using ./setup.sh, and then run the elasticsearch with ./elasticsearch/dev-start.sh I get this:
Starting elasticsearch...
[2015-11-05 08:13:15,614][INFO ][node                     ] [ip-172-31-15-40] version[1.7.1], pid[5262], build[b88f43f/2015-07-29T09:54:16Z]
[2015-11-05 08:13:15,614][INFO ][node                     ] [ip-172-31-15-40] initializing ...
{1.7.1}: Initialization Failed ...
- ElasticsearchException[Missing mandatory plugins [cloud-aws]]

Then I realized you use ElasticSearch 1.7.1 but elasticsearch/dev-install.sh (https://github.com/guardian/grid/blob/master/elasticsearch/dev-install.sh#L29) states a dependency to cloud-aws 2.3.0. I tried to change it to 2.7.1 and it worked. But I'm not sure that was the sorrect way to solve this. So I didn't create a pull request without asking first :)

**Comment by jamesgorrie** [comment]
Hey @husrevo - thanks for spotting this, I've put in a PR #1432 as it should match the version of our [build script](https://github.com/guardian/grid/blob/master/elasticsearch/build.sh#L19). 

Please PR away!

**Comment by husrevo** [comment]
Thanks James, have a nice day :)
