### ISSUE TITLE
Slider obstructing Related labels in Firefox

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#1462]
Hello,

Multiple OSes/FF versions:

![sliderfail](https://cloud.githubusercontent.com/assets/6032869/11266386/1815daae-8e9c-11e5-864c-98acefedd812.jpg)

Regards
Mateusz

**Comment by theefer** [comment]
The scrollbar cannot be styled in FF. We are going to retire (or supersede) this related tags feature with a richer hierarchy of collections. 

So won't fix on this one, just a little patience before something better comes.

**Comment by paperboyo** [comment]
Ah, that's why I've seen it in different places (like too long labels on search page and in panels). No biggie. Thx!
