### ISSUE TITLE
Collections / Collaboration

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#1471]
- [ ] [Create collection model and mapping](https://github.com/guardian/grid/pull/1457).

__Allows:__
* Search by exact collection
* [Search hierarchically](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/analysis-pathhierarchy-tokenizer.html)
* Search by collection bit (not so useful as it negates the point of a hierarchy)

---

- [ ] Tree UI on results page.

__This is the most important to get in front of people to test__.
__Allows:__
* Find images within a collection
* Apply collections to images / add image to collection 

---

- [ ] Edit collections.

__Allows:__
* Discover new collections created by pic editors 
* Create new collections for sub editors

**Comment by alastairjardine** [comment]
Tree UI on results page: how are we thinking of "testing" this?

**Comment by jamesgorrie** [comment]
Closing in favour of #1590
