### ISSUE TITLE
Getting error when trying to start any of the services: Cannot load plugin

### ISSUE THREAD

**Issue by ebrukson** [guardian/grid#1477]
No source available, here is the exception stack trace:

An exception occurred during Plugin [play.api.GlobalPlugin] initialization

java.lang.ExceptionInInitializerError: 
     Global$.beforeStart(Global.scala:9)
     play.api.GlobalPlugin.<init>(GlobalSettings.scala:214)
     sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     java.lang.reflect.Constructor.newInstance(Constructor.java:422)
     play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:132)
     play.api.WithDefaultPlugins$$anonfun$plugins$1$$anonfun$apply$9.apply(Application.scala:130)
     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
     scala.collection.immutable.List.foreach(List.scala:381)
     scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
     scala.collection.immutable.List.map(List.scala:285)
     play.api.WithDefaultPlugins$$anonfun$plugins$1.apply(Application.scala:130)
     play.api.WithDefaultPlugins$$anonfun$plugins$1.apply(Application.scala:166)
     play.utils.Threads$.withContextClassLoader(Threads.scala:21)
     play.api.WithDefaultPlugins$class.plugins(Application.scala:128)
     play.api.DefaultApplication.plugins$lzycompute(Application.scala:402)
     play.api.DefaultApplication.plugins(Application.scala:402)
     play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.utils.Threads$.withContextClassLoader(Threads.scala:21)
     play.api.Play$.start(Play.scala:90)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130)
     scala.Option.map(Option.scala:146)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130)
     play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128)
     scala.util.Success.flatMap(Try.scala:230)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128)
     play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
     scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361)
     scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
     scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
     scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
     scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by jamesgorrie** [comment]
This is normally (and also a badly handled error) of when you haven't got your `.properties` setup for a project. Have you [done this](https://github.com/guardian/grid#properties-files)?

**Comment by ebrukson** [comment]
Thank you for your reply! 

I am having difficulty generating *.properties* file. Any feedback would be appreciated.



ubuntu@GRID:/var/www/grid/public_html/scripts/dot-properties$ ./main.py
2015-11-23 19:02:09,775 generate INFO Connecting to AWS using Profile: media-service in Region us-east-1
Traceback (most recent call last):
  File "./main.py", line 30, in <module>
    main()
  File "./main.py", line 27, in main
    generate_files(aws_profile_name, aws_region, cf_stack, OUTPUT_DIR, properties)
  File "/var/www/grid/public_html/scripts/dot-properties/generate.py", line 56, in generate_files
    connection = _get_connection(aws_profile_name, aws_region)
  File "/var/www/grid/public_html/scripts/dot-properties/generate.py", line 15, in _get_connection
    return cloudformation.connect_to_region(region_name=region_name, profile_name=profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/cloudformation/__init__.py", line 55, in connect_to_region
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/regioninfo.py", line 187, in connect
    return self.connection_cls(region=self, **kw_params)
  File "/usr/local/lib/python2.7/dist-packages/boto/cloudformation/connection.py", line 89, in __init__
    profile_name=profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1100, in __init__
    provider=provider)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 555, in __init__
    profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/provider.py", line 200, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/usr/local/lib/python2.7/dist-packages/boto/provider.py", line 296, in get_credentials
    profile_name)
boto.provider.ProfileNotFoundError: Profile "media-service" not found!

**Comment by ebrukson** [comment]
Figured this out. The issue was resolved when I created AWS creds file for boto as per http://stackoverflow.com/questions/11286479/recommended-way-to-manage-credentials-with-multiple-aws-accounts

**Comment by akash1810** [comment]
> Figured this out. The issue was resolved when I created AWS creds file for boto

Excellent!

The `dot-properties` script uses the `boto` library, which uses the same credentials file as the awscli (since v2.29). These are stored in `~/.aws/credentials`.

It is possible to specify the profile the generator uses in the `settings.ini` file:

> `profile-name` which is the name of an AWS CLI Profile and is defaulted to `media-service` ([link](https://github.com/guardian/grid/tree/master/scripts/dot-properties#configure)).

Please let us know of any other issues.
