### ISSUE TITLE
CloudFormation stack creation issue

### ISSUE THREAD

**Issue by ebrukson** [guardian/grid#1485]
Getting this when attempting to create a stack

15:35:25 UTC-0500	CREATE_FAILED	AWS::DynamoDB::Table	LiveContentPollTable	Resource creation cancelled
Physical ID:media-service-DEV-ubuntu-LiveContentPollTable-1BTFSKA4UNA7Y
15:35:23 UTC-0500	CREATE_FAILED	AWS::Lambda::Function	UsageUpdaterFunction	Error occurred while getting the object from S3. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist.

**Comment by kenoir** [comment]
You need to deploy the` usage-updater` artefact to S3 before running the CF uodate. 

Although you are probably better off omitting the CF for that service as the `usage` service is highly tied to Guardian architecture.

**Comment by akash1810** [comment]
> Although you are probably better off omitting the CF for that service as the usage service is highly tied to Guardian architecture.

I'll take a look at putting these resources into a secondary, optional, stack as they're not core to running the Grid in general.

**Comment by akash1810** [comment]
Hi @ebrukson, if you pull master you can use the [create-stack.sh](https://github.com/guardian/grid/blob/master/cloud-formation/scripts/create-dev-stack.sh) script.

**Comment by ebrukson** [comment]
Thank you for looking into this.

I am getting an error now

ubuntu@GRID:/var/www/grid/public_html/cloud-formation/scripts$ ./create-dev-stack.sh
error: startswith is not defined
.Buckets[] | select(.Name | startswith("media-service-dist")) | .Name
                            ^^^^^^^^^^
1 compile error
[Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
Creating bucket media-service-dist-jahnishiengichiwieho
make_bucket: s3://media-service-dist-jahnishiengichiwieho/
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument subcommand: Invalid choice, valid choices are:

list
Uploading template to s3://media-service-dist-jahnishiengichiwieho/cloudformation/DEV/media-service-DEV-null.template
upload: ../dev-template.json to s3://media-service-dist-jahnishiengichiwieho/cloudformation/DEV/media-service-DEV-null.template
Creating stack media-service-DEV-null
A client error (ValidationError) occurred when calling the CreateStack operation: TemplateURL must be an Amazon S3 URL.

**Comment by akash1810** [comment]
> error: startswith is not defined

Suggests you may not have [jq](https://stedolan.github.io/jq/) installed?

I'll update the documentation soon, however, please note you'll need jq and pwgen installed.

**Comment by ebrukson** [comment]
I have both. The issue is with referencing the S3 bucket

<strong>Uploading template to s3://media-service-dist-miecheosochohsohdoog/cloudformation/DEV/media-service-DEV-null.template
upload: ../dev-template.json to s3://media-service-dist-miecheosochohsohdoog/cloudformation/DEV/media-service-DEV-null.template
Creating stack media-service-DEV-null
A client error (ValidationError) occurred when calling the CreateStack operation: TemplateURL must be an Amazon S3 URL.
</strong>

**Comment by akash1810** [comment]
Seems like there's a problem determining the stack name. What does:

```
source ./stack-name.sh && echo $STACK_NAME
```
return?

**Comment by ebrukson** [comment]
media-service-DEV-null

**Comment by akash1810** [comment]
hmm, what about

```sh
aws iam get-user
```

Thanks for your patience!

**Comment by ebrukson** [comment]
$ aws iam get-user
{
    "User": {
        "Arn": "arn:aws:iam::283711680364:root",
        "CreateDate": "2013-11-25T19:32:46Z",
        "UserId": "283711680364"
    }
}

**Comment by akash1810** [comment]
Ah! You're using your aws root credentials. We've not accounted for this scenario! We don't use root credentials, instead we have individual iam users (with admin access).

I'd advise [creating an iam user](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html).

Again, we'll update the docs with a note to this effect.

**Comment by akash1810** [comment]
Also note that you must have specified a region when creating an awscli profile. If you hadn't you can always add it by editing `~/.aws/config` adding:

```
[profile foo]
region = bar
```

**Comment by ebrukson** [comment]
Created an admin user which solved the user naming issue, however *create-dev-stack.sh* still fails with the same error

$ ./create-dev-stack.sh
Creating bucket media-service-dist-da5ac78d37fc6e4cc3de
make_bucket: s3://media-service-dist-da5ac78d37fc6e4cc3de/
usage: aws [options] <command> <subcommand> [parameters]
aws: error: argument subcommand: Invalid choice, valid choices are:

list
Uploading template to s3://media-service-dist-da5ac78d37fc6e4cc3de/cloudformation/DEV/media-service-DEV-grid-user.template
upload: ../dev-template.json to s3://media-service-dist-da5ac78d37fc6e4cc3de/cloudformation/DEV/media-service-DEV-grid-user.template
Creating stack media-service-DEV-grid-user
A client error (ValidationError) occurred when calling the CreateStack operation: TemplateURL must be an Amazon S3 URL.

**Comment by akash1810** [comment]
It might be better to debug your particular issue in gitter? [![Join the chat at https://gitter.im/guardian/grid](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/guardian/grid?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

However, I think the problem lies in `aws configure get region` not returning anything. The value of that is used to form the url of the template in S3, hence:

> A client error (ValidationError) occurred when calling the CreateStack operation: TemplateURL must be an Amazon S3 URL.
