### ISSUE TITLE
Better reliability and performance with selections

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#1508]
Hello,

Something you probably are aware of, just wanted to register it as an issue(s):
1. Selections are unreliable when you haven't _seen_ all images in between the first and last. To test, select an image, drag a slider quickly (but not too far, see pt. 2) and shift+select the last image. Then slowly drag past all the images in the selection and notice that, actually, not all are selected. Deselected are the ones that are just showing up now in front of you.
2. Selections/deselections are very slow. Here are some poor-man's stats:

Latest Chrome on MacPro: 140 images: 40sec and one dialog box (unresponsive site). Deselection 1s.
Latest Firefox on MacPro: 258 images: **5min 20sec** and **24** dialog boxes (unresponsive script). Deselection 3s.

I do think it's not a priority. Especially, no. 2. But no. 1 may bring a very unpleasant surprises. Even more so, if they get unnoticed (like with batch metadata editing).

Regards
Mateusz

**Comment by NickPapacostas** [comment]
![](i.imgur.com/IZG0gNr.gif)

**Comment by paperboyo** [comment]
3. Some operations on selections are unreliable, e.g. downloading a ZIP (contains just a random subset of selected photos), adding to library (“Failed to add to library. Please try again.”).

**Comment by paperboyo** [comment]
This is much better, thanks mainly to https://github.com/guardian/grid/pull/2905 and https://github.com/guardian/grid/pull/2917. Next step would require using bulk APIs…
