### ISSUE TITLE
No results when searching 'Will' 

### ISSUE THREAD

**Issue by tsop14** [guardian/grid#1523]
Searching

[Will](https://media.gutools.co.uk/search?query=Will) - no images

[Will "Self"](https://media.gutools.co.uk/search?query=Will%20%22Self%22) - no images

 ["Will Self"](https://media.gutools.co.uk/search?query=%22Will%20Self%22) -  images with "self" in description 

["Will" Self](https://media.gutools.co.uk/search?query=%22Will%22%20Self) - images of Will Self. ✔️

I think as 'Will' is ignored, "Will Self" becomes a type of "Self". 
There are also different number of results for searching: 
" Self"
"Self"
Self" 

Expected: Where there's a 'will'... there are images with 'will' in the description 

Perhaps similar to #1422

**Comment by AWare** [comment]
Fixed in #3130.
