### ISSUE TITLE
Unauthed users aren't redirected to sign in

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#1563]
There have been two cases we've seen of this:
- ~~When a users 2FA expires~~
- ~~When they aren't signed in at all.~~
- When logged into a Google account other than you@guardian.co.uk

Hopefully thinking - but maybe one will fix the other.

**Comment by theefer** [comment]
Possibly also occurs if they are signed in with multiple accounts and don't have any panda cookie (not even expired) to hint at which account to use.

**Comment by kenoir** [comment]
Think this one got resolved.

**Comment by theefer** [comment]
This still seems to be happening if you're logged into a non-Guardian Google account. You end up on a blank screen.

**Comment by akash1810** [comment]
Another scenario:

- Your Google session has expired - i.e. going to gmail prompts for a password. In this case, the console gives an error that the oauth iframe cannot be embedded. Clicking login on the red banner doesn't do much as you have to physically login to gmail in a new tab.

**Comment by akash1810** [comment]
Largely fixed in https://github.com/guardian/grid/pull/2404.
