### ISSUE TITLE
Elasticsearch Reindexing 

### ISSUE THREAD

**Issue by NickPapacostas** [guardian/grid#1585]
Updates
-----------
- [x] Thrall writes to multiple indexes
- [x] Reindex script recurses to ensure no writes were missed

TODOS (unordered)
---------------------------
- [x] add timestamp to sqs messages (?) 
- [x] figure out if ES bulk import is transactional (i.e. writes get queued up while a bulk import is going on)
   - not too helpful in the end, but interesting: https://www.elastic.co/blog/found-keeping-elasticsearch-in-sync
- [x] talk to capi about their approach
I just wanted to jot down some thoughts on reindexing and have a place where we could list the issues as we see them. 

Right now it seems like reindexing elasticsearch (to update mappings etc) is a risky operation. 

(new) Proposal
---------------------

For changes to fields (analyzers / copyTo / adding fields etc.) NOT changing core type of field: 
1. Make change to Mappings file and create PR (e.g. https://github.com/guardian/grid/pull/1744)
2. Make code change and create PR (e.g. https://github.com/guardian/grid/pull/1745)
3. Merge Mappings PR 
4. Deploy
5.**  STOP BACKUP CRON ON ES MASTER **
6. Run Reindex on worker (at this point writing is happening on both old and new index)
    - ssh into ec2 instance "NickP worker - ENV)
    - clear out the home dir (to get rid of old versions of the project)
    - copy the "Download Zip" button url from github for master
    - use wget to pull the code down
    - unzip
    - cd into the project
    - run ```$ ./sbt```
    - ``` scripts/run Reindex LOCAL_IP_OF_ES_BOX ``` (e.g. 172.31.36.85)
7. Switch Read alias, confirm it's all working
8. Remove Write alias from old index
9. Merge code PR
10. Deploy
11. :fireworks: glory :fireworks: 

For breaking changes to Mappings:

TBD but i got ideaz

Current Process
----------------------
From what I understand the current process looks like this:
1. create new index with updated mappings

2. begin bulk copy from old index 

3. spin up new sns/sqs queue to hold updates that have happened since bulk update was called 
-- simultaneously updates continue to be written to original old index from old sqs queue 

4. once bulk insert into new index is finished, flush new sqs into new index

5. switch add alias name to new index

6.  delete old index

A simpler proposal (completed):
-------------------------
this can be combined with the idea of having thrall publish sqs changes to a "write" alias

1. reindex from old index
2. call a bulk-update for changes since reindex was triggered
3. repeat until there are none 
4. switch alias

Reasons it might suck:
-----------------------------
I think the concern with this solution is probably around non-chronological updates.  i.e. thralls pumping updates into the new index as it's getting bulk-inserted and the order of updates can't be guaranteed. I need to learn more about how ES handles request during bulk inserts to know if that's an issue. 

However one thing to point out is that our current process (assuming i got it right) is also at risk of this because the sqs queue isn't "order-guaranteed". Although I suppose the advantage is that you can guarantee that the bulk update happens _before_ the queue gets flushed into the new index

Resources:
---------------

* http://www.mavengineering.com/blog/2014/02/12/seamless-elasticsearch-reindexing/
  - seems to imply that we can just do the alias strategy and it'll work
  - confirmed here (downvoted for SO rules not content) : http://stackoverflow.com/questions/15910612/elasticsearch-reindexing-how-do-you-direct-updates-to-the-new-index-while-it-is

* https://blog.codecentric.de/en/2014/09/elasticsearch-zero-downtime-reindexing-problems-solutions/ 
  - seems to imply that the alias solution *wont* work for deletes and updates but the comments offer different solutions, one of which being our current "second queue" option

**Comment by akash1810** [comment]
> 6. Run Reindex on worker (at this point writing is happening on both old and new index)

What's the behaviour when a write (metadata update, delete etc) comes through for a document that doesn't yet exist in the new index?

**Comment by NickPapacostas** [comment]
@akash1810 the message gets written on the first index (where the doc exists) and fails on the second, goes back on the queue and then gets replayed (with the same effect). The majority of these though are index requests for new images, so I haven't seen those stack up significantly.

But, if _all_ the requests are failing (because the indices are incompatible (like my flub on tuesday)) then you will see a spike in failed requests.

**Comment by akash1810** [comment]
So an SQS message is only deleted iff thrall successfully writes to all indexes under the write alias? Cool!

**Comment by kenoir** [comment]
:+1:
