### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#1590]
Things required:
- [x] [Create collections](https://github.com/guardian/grid/pull/1576)
- [x] [Add to collections from results](https://github.com/guardian/grid/pull/1576)
- [x] Add to collections on upload
- [x] [View collections on results](https://github.com/guardian/grid/pull/1579)
- [x] View collections on image page
- [x] [Tree state saving](https://github.com/guardian/grid/pull/1593)

**Comment by tsop14** [comment]
- [ ] Remove image from collection

**Comment by akash1810** [comment]
- [ ] hide panels when printing

**Comment by kenoir** [comment]
- [ ] Remove collection from image when collection deleted

**Comment by kenoir** [comment]
This is substantially complete.
