### ISSUE TITLE
suggested labels on image page not visible

### ISSUE THREAD

**Issue by akash1810** [guardian/grid#1624]
![labels](https://cloud.githubusercontent.com/assets/836140/12292455/18041020-b9e5-11e5-9778-018e92022f58.gif)

Its a CSS thing as keyboard navigation works.

**Comment by paperboyo** [comment]
Yes, yes - me to. Also, but that's going to sound terribly vague: sometimes hitting return/enter does not work for committing. No pattern to it apart from the fact that's it's almost always first thing on a new day at work, then it starts working. Sort of like me.

**Comment by akash1810** [comment]
> hitting return/enter does not work for committing

Do you see any error messages when this happens? I can't reproduce, but grab us when it happens again please!

**Comment by paperboyo** [comment]
Happens mostly on full picture page (in viewer). Won't not work now. Will do, thanks!

**Comment by paperboyo** [comment]
![image](https://user-images.githubusercontent.com/6032869/41374949-8241e6e6-6f4c-11e8-9248-cd1f90767df5.png)

Can’t repro, safe to close, @guardian/grid-admins?

**Comment by akash1810** [comment]
yep!
