### ISSUE TITLE
single image download in FF broken

### ISSUE THREAD

**Issue by akash1810** [guardian/grid#1707]
As noted my Mark on Guide.

Downloading a single image in firefox does not trigger a file download, it opens the image in a new tab instead.

Looking at the [docs](https://developer.mozilla.org/en/docs/Web/HTML/Element/a), a possible reason is:

> This attribute is only honored for links to resources with the same-origin.

Currently we're linking to an S3 object, on an S3 domain.

**Comment by akash1810** [comment]
Fixed in #1709

**Comment by paperboyo** [comment]
:gem:
