### ISSUE TITLE
Add "Unusable" state.

### ISSUE THREAD

**Issue by kenoir** [guardian/grid#1736]
Add the ability to flag some images as "unusable" without having to remove them entirely.

Unusable images would have no visible crops and it would not be possible to create further crops.

**Comment by theefer** [comment]
Would they still be draggable into InDesign?

**Comment by paperboyo** [comment]
Downloadable and reuploadable and the ready for use? Just kidding...

**Comment by theefer** [comment]
I was going to suggest preventing download, which makes sense, but would be possible to work around as long as you can see the picture.

**Comment by kenoir** [comment]
Would require some work from @blishen to get this to work for the print workflow.

**Comment by theefer** [comment]
I can't remember what drag metadata it relies on, and wonder if we could just attach less metadata in that state?

**Comment by paperboyo** [comment]
I think with current Usage Rights model in place, it’s either completely or almost there. Safe to close, @akash1810?

**Comment by akash1810** [comment]
> I think with current Usage Rights model in place

The current usage rights model doesn't prevent you from cropping, it just makes it look scary with big red messages. Deny leases, however does solve this. Closing. 🎉
