### ISSUE TITLE
Make collections 'top bar' sticky

### ISSUE THREAD

**Issue by tsop14** [guardian/grid#1775]
So you can always see the edit button - most people are in a remembered state scrolled down so they can no longer see the wonderful edit button.

**Comment by akash1810** [comment]
I've got a branch for this on my machine 😊. Will PR it soon.

**Comment by tsop14** [comment]
Perfect! 👌

**Comment by NickPapacostas** [comment]
https://github.com/guardian/grid/pull/1800
