### ISSUE TITLE
Crop dimensions not synchronised to crop frame

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#1858]
Hello,

Ratio is not always maintained while using input boxes:

![crop dimensions](https://cloud.githubusercontent.com/assets/6032869/14590128/6529aaa8-04eb-11e6-9857-daa92c829826.gif)

Also, when one changes the dimensions through input boxes the origin point is in top left. I think it would be better if it would be in the centre.

Regards
Mateusz

**Comment by kenoir** [comment]
This is only true where increasing one dimension while the other is at maximum, crops created are capped at the maximum within the ratio constraint (so are not "broken").

**Comment by paperboyo** [comment]
This is (mostly) fixed. Closing for now.
