### ISSUE TITLE
Leases cannot be batch applied...

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#1906]
...neither on the Upload page (there, they cannot be applied at all!) nor _via_ info panel. I think all metadata operations should be consistent and when there is a new one added, it should work through all existing channels. Collections can be (batch-)applied on an Upload page, but should also be possible to be (batch-)applied _via_ an info panel. Labels are working correctly - you can add them everywhere - and should be a good model here.

Of course, most users would be able to batch apply leases _via_ the info panel only when having permissions for all selected images, but there is already a precedence: batch editing e.g. a description doesn’t work if at least one image in a selection is not permitted for editing. Whether it should work for only those images from a selection for which user has rights is another matter, but at least it works at all.

This is a suggestion that came up when I was fantasizing about soon-to-be-probably-necessary upload of ~550 images that *may* all need leases on them :-)

**Comment by kenoir** [comment]
Amen.
On Mon, 23 May 2016 at 20:02, Mateusz <notifications@github.com> wrote:

> ...neither on the Upload page (there, they cannot be applied at all!) nor
> *via* info panel. I think all metadata operations should be consistent
> and when there is a new one added, it should work through all existing
> channels. Collections can be (batch-)applied on an Upload page, but should
> also be possible to be (batch-)applied *via* an info panel. Labels are
> working correctly - you can add them everywhere - and should be a good
> model here.
>
> Of course, most users would be able to batch apply leases *via* the info
> panel only when having permissions for all selected images, but there is
> already a precedence: batch editing e.g. a description doesn’t work if at
> least one image in a selection is not permitted for editing. Whether it
> should work for only those images from a selection for which user has
> rights is another matter, but at least it works at all.
>
> This is a suggestion that came up when I was fantasizing about
> soon-to-be-probably-necessary upload of ~550 images that *may* all need
> leases on them :-)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/issues/1906>
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by NickPapacostas** [comment]
Hey Mateusz. Yup, we know ^_^

**Comment by paperboyo** [comment]
Closing as it's being worked on and the issue is thus pointless and does not have any added value.

**Comment by NickPapacostas** [comment]
we're almost there @paperboyo ... so close!

**Comment by kenoir** [comment]
No closing issues until they're done.

**Comment by paperboyo** [comment]
> No closing issues until they're done.

Good policy, sorry then :laughing: But instead of reopening this one, I would reopen The Rabbit Hole (https://github.com/guardian/grid/issues/1117) instead :stuck_out_tongue_winking_eye:
