### ISSUE TITLE
Use Auditing API

### ISSUE THREAD

**Issue by kenoir** [guardian/grid#1928]
To start with for user delete events - need to add user id into delete requests reaching Thrall.

**Comment by kenoir** [comment]
See: https://github.com/guardian/tagmanager/pull/231/files

**Comment by kenoir** [comment]
Will need to PR: https://github.com/guardian/auditing-thrift-model/blob/master/src/main/thrift/auditing.thrift

**Comment by akash1810** [comment]
Auditing is no longer a running service. Closing.
