### ISSUE TITLE
assets/jspm_packages/system.js Not found in kahuna

### ISSUE THREAD

**Issue by asosoman** [guardian/grid#2027]
After fighting with all the documentation and installing it, we were able to get to the "Loading the grid" frontpage. 

But then it stays that way. Seems like a js file is not found and cannot continue. As far as I know, there is nothing we can do to fix it.

Request URL:https://media.xxxx.xxxx/assets/jspm_packages/system.js
Request Method:GET
Status Code:404 Not Found

Thanks!

**Comment by kenoir** [comment]
Have you tried running the setup in the kahuna directory?

**Comment by asosoman** [comment]
After checking everything, that was missing. Just got halfway until you need to log with github credentials.

Now, we only lack the panda part... Thanks!
