### ISSUE TITLE
Installation guide is outdated.

### ISSUE THREAD

**Issue by PriteshJain** [guardian/grid#2030]
I am trying to explore this project but linux installation guide is not upto date. it point to some devops project that does not exist. Could you please help with updated steps for trying this project.

**Comment by PriteshJain** [comment]
the https://github.com/guardian/dev-nginx link is broken in readme. Can you please update the link. 🙏

**Comment by jennysivapalan** [comment]
Hi @PriteshJain,

The dev-nginx links to a private repo in the Guardian organisation. It's a helper script
used across Guardian projects to install SSL certificates and setup a local nginx config.
It uses the settings in [nginx-mapping.yml](https://github.com/guardian/grid/blob/master/nginx-mappings.yml). 

Sorry the documentation isn't clearer. If you're trying to get this up and 
running you need to create your nginx config file. For each of the apps listed in nginx-mapping.yml you'll need to add the following to a nginx config file for the project (I've taken out Guardian specific values)

```
server {
  listen 443;
  server_name example.com;

  location / {
    proxy_pass http://localhost:[port-no];
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect default;
    proxy_buffering off;
  }

  ssl on;
  ssl_certificate     [use-own-value].crt;
  ssl_certificate_key [use-own-value].key;

  ssl_session_timeout 5m;

  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers on;
}
server {
  listen 80;
  server_name example.com;

  # redirect all HTTP traffic to HTTPS
  return 301 https://$host$request_uri;
}
``` 

We'll aim to add to get the README updated to be clearer.

I hope that helps.

**Comment by akash1810** [comment]
The `dev-nginx` repo has now been made public 🎉 .

Closing this issue.
