### ISSUE TITLE
Unable to auth through the iframe when opening The Grid in Composer

### ISSUE THREAD

**Issue by rcrphillips** [guardian/grid#257]
Refused to display 'https://accounts.google.com/AccountChooser?service=lso&continue=https%3A%2F….com%26hl%3Den%26from_login%3D1%26as%3D759d38844d7b4d3&btmpl=authsub&hl=en' in a frame because it set 'X-Frame-Options' to 'DENY'.

**Comment by theefer** [comment]
This is only if third-party cookies are disabled. We have now added an exception for the google auth domain on all managed computers so closing this.
