### ISSUE TITLE
IllegalStateException: Unable to download public key

### ISSUE THREAD

**Issue by cstrd** [guardian/grid#2586]
When I run GRID on my machine I get this error in browser, Please Help.
```
Unexpected exception
IllegalStateException: Unable to download public key

No source available, here is the exception stack trace:
->java.lang.IllegalStateException: Unable to download public key
     com.gu.pandomainauth.Settings$.errorToThrowable(Settings.scala:55)
     com.gu.pandomainauth.PanDomainAuthSettingsRefresher.<init>(PanDomainAuthSettingsRefresher.scala:35)
     com.gu.mediaservice.lib.auth.Authentication.buildPandaSettings(Authentication.scala:85)
     com.gu.mediaservice.lib.auth.Authentication.panDomainSettings$lzycompute(Authentication.scala:43)
     com.gu.mediaservice.lib.auth.Authentication.panDomainSettings(Authentication.scala:43)
     com.gu.pandomainauth.action.AuthActions.settings(Actions.scala:26)
     com.gu.pandomainauth.action.AuthActions.$init$(Actions.scala:71)
     com.gu.mediaservice.lib.auth.Authentication.<init>(Authentication.scala:26)
     com.gu.mediaservice.lib.play.GridComponents.<init>(GridComponents.scala:35)
     ThrallComponents.<init>(ThrallComponents.scala:8)
     AppLoader$$anonfun$$lessinit$greater$1.apply(AppLoader.scala:3)
     AppLoader$$anonfun$$lessinit$greater$1.apply(AppLoader.scala:3)
     com.gu.mediaservice.lib.play.GridAppLoader.load(GridAppLoader.scala:11)
     play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
     play.utils.Threads$.withContextClassLoader(Threads.scala:21)
     play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
     play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
     play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:241)
     play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:138)
     akka.stream.impl.fusing.MapAsyncUnordered$$anon$26.onPush(Ops.scala:1304)
     akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
     akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
     akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
     akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
     akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
     akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
     akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
     akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
     akka.actor.Actor.aroundReceive(Actor.scala:517)
     akka.actor.Actor.aroundReceive$(Actor.scala:515)
     akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
     akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
     akka.actor.ActorCell.invoke(ActorCell.scala:557)
     akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
     akka.dispatch.Mailbox.run(Mailbox.scala:225)
     akka.dispatch.Mailbox.exec(Mailbox.scala:235)
     akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
     akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
     akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
     akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cstrd** [comment]
Hello @akash1810 Sir can you please help!

**Comment by cstrd** [comment]
@mbarton  Sir can you please help

**Comment by mbarton** [comment]
Hi @cstrd. To fix this error you'll need to set up our authentication library [pan-domain-authentication](https://github.com/guardian/pan-domain-authentication). See the instructions in the README there.

Once you have it set up you can edit your settings files to add the appropriate `panda.*` settings follow this PR: https://github.com/guardian/grid/pull/2394.

The reason you get an error initially is because the default is to read the auth settings for our deployment which are not public. We're working on making a better quick-start guide for the Grid that covers things like this

**Comment by cstrd** [comment]
@mbarton @akash1810  I am following the steps you mentioned, but I am unable to complete the "Generic OAuth2 Provider" step mentioned in [https://github.com/guardian/pan-domain-authentication](https://github.com/guardian/pan-domain-authentication)
Can you please give  a brief description of how it needs to setup and how are all these components connected.
Thanks

**Comment by mbarton** [comment]
We're still working on a full setup guide and will share it as soon as we can.

In the meantime, what error/problems are you having setting up pan-domain-authentication?

**Comment by cstrd** [comment]
@mbarton How to integrate it to grid, there is an example code given in the repository but where do I add the files in grid folder.
Thanks!

**Comment by mbarton** [comment]
Ah OK. The configuration for pan-domain-authentication itself needs to go in an S3 bucket you create, following the instructions in the README in the other repo.

Once you've got that set up, you can update the configuration files in `/etc/gu` to including the settings described in [this PR](https://github.com/guardian/grid/pull/2394) (`panda.bucketName` etc).

**Comment by cstrd** [comment]
@mbarton
I have followed your instructions and here is what my [/etc/gu](https://github.com/cstrd/etc-gu) contains. 
and I have created pan-domain-auth bucket in s3 and here are the files in it [file1](https://pan-domain-auth.s3.amazonaws.com/grid.local.public) 
[file2](https://pan-domain-auth.s3.amazonaws.com/grid.local.settings) These files were generated by cognito stack in other s3 buckets using this command ./cognito/generate-settings.sh ${CLOUDFORMATION_STACK} ${REGION}
Also I have added, `libraryDependencies += "com.gu" %% "pan-domain-auth-verification" % "0.2.13";` line to build.sbt in grid.
and in the Cognito config, I put CALLBACK URL as `http://localhost`
I have done till 3rd step from the [docs](https://github.com/guardian/grid/tree/master/docs).
Here is what I get when I run ./dev-start.sh and go to localhost:9002

> `IllegalStateException: Unable to download public key
> 
> No source available, here is the exception stack trace:
> ->java.lang.IllegalStateException: Unable to download public key
>      com.gu.pandomainauth.Settings$.errorToThrowable(Settings.scala:55)
>      com.gu.pandomainauth.PanDomainAuthSettingsRefresher.<init>(PanDomainAuthSettingsRefresher.scala:35)
>      com.gu.mediaservice.lib.auth.Authentication.buildPandaSettings(Authentication.scala:85)
>      com.gu.mediaservice.lib.auth.Authentication.panDomainSettings$lzycompute(Authentication.scala:43)
>      com.gu.mediaservice.lib.auth.Authentication.panDomainSettings(Authentication.scala:43)
>      com.gu.pandomainauth.action.AuthActions.settings(Actions.scala:26)
>      com.gu.pandomainauth.action.AuthActions.$init$(Actions.scala:71)
>      com.gu.mediaservice.lib.auth.Authentication.<init>(Authentication.scala:26)
>      com.gu.mediaservice.lib.play.GridComponents.<init>(GridComponents.scala:35)
>      ThrallComponents.<init>(ThrallComponents.scala:8)
>      AppLoader$$anonfun$$lessinit$greater$1.apply(AppLoader.scala:3)
>      AppLoader$$anonfun$$lessinit$greater$1.apply(AppLoader.scala:3)
>      com.gu.mediaservice.lib.play.GridAppLoader.load(GridAppLoader.scala:11)
>      play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
>      play.utils.Threads$.withContextClassLoader(Threads.scala:21)
>      play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
>      play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:124)
>      play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:241)
>      play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:138)
>      akka.stream.impl.fusing.MapAsyncUnordered$$anon$26.onPush(Ops.scala:1304)
>      akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
>      akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
>      akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
>      akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
>      akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
>      akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
>      akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
>      akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
>      akka.actor.Actor.aroundReceive(Actor.scala:517)
>      akka.actor.Actor.aroundReceive$(Actor.scala:515)
>      akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
>      akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
>      akka.actor.ActorCell.invoke(ActorCell.scala:557)
>      akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
>      akka.dispatch.Mailbox.run(Mailbox.scala:225)
>      akka.dispatch.Mailbox.exec(Mailbox.scala:235)
>      akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>      akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>      akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>      akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

Can you look into it, what am I  missing.
Thanks

**Comment by cstrd** [comment]
@mbarton Sir please have a look at it ! 
Thanks!

**Comment by mbarton** [comment]
Do the Amazon credentials you are running with have `s3:GetObject` permission to `s3://cognito-settingsbucket-sycde3ha71md/grid.local.settings`? Unfortunately it looks like the Panda library is eating the original cause of the error but you could find out what it is by putting a breakpoint on the code that downloads the settings file: https://github.com/guardian/pan-domain-authentication/blob/master/pan-domain-auth-verification/src/main/scala/com/gu/pandomainauth/Settings.scala#L26.

Just as an aside, I can see the two settings file you linked to are in an S3 bucket called `pan-domain-auth`, rather than `cognito-settingsbucket-sycde3ha71md`. Is this a brand new bucket you made to share them? The private settings file `grid.local.settings` is publically accessible and contains your authentication private key. That file should **not** be publically accessible. I'm checking because I want to make sure our cognito scripting did not upload it like that?

**Comment by cstrd** [comment]
@mbarton  I have tried with both the bucket names "cognito-settingsbucket-sycde3ha71md" and "pan-domain-auth", second one is made by me and  I have intentionally made "grid.local.settings" file to public for sharing with you. And yes I have made a new policy with s3:GetObject permissions, Still the issue persists.
Thanks

**Comment by cstrd** [comment]
@mbarton How do I add a breakpoint in Settings.scala file, I can't find that file in the grid project. It's in pan-domain-authentication folder.

**Comment by CaerphillyMediaLtd** [comment]
I'm getting the same failure to download public key error? Did you manage to solve it?

The installation documentation on this project is a mess to be honest. Missed out steps, outdated parts, etc.

**Comment by akash1810** [comment]
Quite a late response... #2927 looks like it'll help here. Would be interested to get your feedback on it.

**Comment by akash1810** [comment]
Closing - https://github.com/guardian/grid/pull/2927 should solve this. Please raise a new issue if needed.
