### ISSUE TITLE
Merge config change contributions

### ISSUE THREAD

**Issue by mbarton** [guardian/grid#2676]
The following PRs refactoring out some config have been open for quite a while:

- [ ] https://github.com/guardian/grid/pull/2995 (supercedes https://github.com/guardian/grid/pull/2612)
- [ ] https://github.com/guardian/grid/pull/2614
- [ ] https://github.com/guardian/grid/pull/2618 (depends on previous two)
- [ ] https://github.com/guardian/grid/pull/2620 (depends on previous three)
- [ ] https://github.com/guardian/grid/pull/2622 (depends on previous four)

We'd like to get them merged but will need to verify that we are still correctly parsing the affected fields and assigning rights correctly.

Here's the plan for merging and testing each one:

- Extract out JSON config from the current code on `master`
- Run in TEST with config and upload an image
- Check the API response is the same
  - NB: signed URLs may be different but that won't matter

cc @jamie-pitts @felixcs1

**Comment by jamie-pitts** [comment]
That's great to hear @mbarton appreciate there's quite a bit of testing and work to do on your side for these, so no worries for them being open for a while. Let us know if you have any problems!

**Comment by akash1810** [comment]
> Check the API response is the same

We can use [grid-cli](https://github.com/guardian/grid-cli) for this 🎉.  Here's a little script - https://gist.github.com/akash1810/c681d57155f8e48e95214ca39a8f8cdf.

**Comment by paperboyo** [comment]
As the PRs mentioned are all closed or superseded, I will close this even though probably more configuration needs to move out of code. But it won’t be tracked by this issue.
