### ISSUE TITLE
Make additional image fields visible on the UI

### ISSUE THREAD

**Issue by ochiengolanga** [guardian/grid#3167]
## Short description
Currently there's a finite set of visible fields in the UI which are present in the `$.metadata` ([see ImageMetadata.scala](https://github.com/guardian/grid/blob/9588b1c2b5074866ffd11a3dd8176592271cb432/common-lib/src/main/scala/com/gu/mediaservice/model/ImageMetadata.scala#L10)) in the `GET image by id` JSON payload i.e. (_`dateTaken, description, credit, creditUri, byline, bylineTitle, title, copyright, supplier…`_). Extra useful metadata exists in the fileMetadata ([see  FileMetadata.scala](https://github.com/guardian/grid/blob/9588b1c2b5074866ffd11a3dd8176592271cb432/common-lib/src/main/scala/com/gu/mediaservice/model/FileMetadata.scala#L10)) fields stored in Elasticsearch as part of the Image document. However, the FileMetadata is currently not visible on the UI despite an API endpoint existing “/images/{:imageId}/fileMetadata” on the media-api service and the presence of some useful information in fileMetadata. 

This proposal introduces an approach to surface some of the metadata fields that have been extracted from the image and stored in Elasticsearch by making them visible through configuration with some UX considerations.

An admin / developer should be able to configure which fields from the fileMetadata they would like users to see, search by and specify a more human readable name of the metadata field aka an alias e.g. a user would prefer to see `Programme Number` rather than `xmp.bbc:ProgrammeNumber`.

NB: On the search, this proposal intends to improve the UX on the feature introduced by [BBC] Search on the value of arbitrary fields (https://github.com/guardian/grid/pull/3132) PR.

## Approach

1. Introduce a model that represents field aliases configuration with the following configuration parameters "`elasticsearchPath`", “`label`”, “`displaySearchHint`” and “`alias`” that's read from kahuna.conf and media-api.conf
2. Use the field aliases configuration to create a JSON object `aliases` with filemetadata fields that's added to the `GET image by id` JSON payload.
3. Introduce a “show image metadata” UI component that renders filemetadata fields in the `aliases` JSON object.

**Comment by AWare** [comment]
2/3: can we store this in localStorage instead?

**Comment by paperboyo** [comment]
The original issue and this 

> 2/3: can we store this in localStorage instead?

assume this is configurable by a user. Even if all users would be willing and able to do that, I think this is unnecessary and potentially can lead to chaos (lees so with different views of metadata, definitely with different aliases).

I think configuring it once per deployment, maybe in the future per silo, will help to keep sanity and consistency. Again, this applies especially to aliases, but not only. Imagine someone sending a search URL referring to contents of a specific field to someone else, but the latter wouldn’t see it. Or have it named differently… They both call support and both give different names for what they are seeing 😜.

**Comment by ochiengolanga** [comment]
> 2/3: can we store this in localStorage instead?

Hi @AWare,

2/3 describes the implementation on the metadata-service and it's persistent store in the backend.

The fetched metadata configurations by the UI can be stored in localStorage. I've updated the approach (4) to indicate this.

I'll be more than happy to receive other alternative approaches for the backend and frontend implementation.

**Comment by ochiengolanga** [comment]
> The original issue and this
> 
> > 2/3: can we store this in localStorage instead?
> 
> assume this is configurable by a user. Even if all users would be willing and able to do that, I think this is unnecessary and potentially can lead to chaos (lees so with different views of metadata, definitely with different aliases).
> 
> I think configuring it once per deployment, maybe in the future per silo, will help to keep sanity and consistency. Again, this applies especially to aliases, but not only. Imagine someone sending a search URL referring to contents of a specific field to someone else, but the latter wouldn’t see it. Or have it named differently… They both call support and both give different names for what they are seeing .

Hi @paperboyo ,

Allowing a user to configure this will definitely lead to chaos. I've updated the description and replaced `user` with `admin / developer` to now indicate centralized configuration. Thanks!

**Comment by sihil** [comment]
This proposal generally looks great.

With regard to 2: I'd seriously consider reading this from configuration initially rather than going to the effort of creating an S3 or Dynamo store. I'm aware that you're still using the legacy properties format of configuration so this might be the right time to switch (there is a migration tool, see https://github.com/guardian/grid/pull/3037) as HOCON let's you express structured concepts far more easily.

With regard to 3: I think the concerns here are closer to the media-api than the metadata service (which is about editing the metadata rather than viewing it). At the moment I think you are suggesting that the client reads the `fileMetadata` endpoint and merges in the metadata. I wonder if it might be nicer/better to merge this custom metadata into the main image response on the server side so it's available without any further calls. In addition, if the shape is correct then we would not need a separate configuration for this as it would be in the main response.

WRT 4: I'd avoid caching this locally. If we need config then we should get it from an API endpoint each time. Not doing so means that we might end up with caching issues. If performance proves to be a problem then we can optimise later.

Would like to see @akash1810 have a look at this too.

**Comment by ochiengolanga** [comment]
Thanks @sihil for the recommendations on the approach.

**Comment by akash1810** [comment]
This would be an excellent feature!

I think we might be able to simplify the process a little, whilst making use of existing patterns in the project.

> 1. Introduce a model that represents metadata configuration with the following configuration parameters “visible”, “searchable” and “alias”.

This suggests we know what fields we want to display and will not allow the entire `fileMetadata` block to be rendered? We've experienced some noise in `fileMetadata` so this sounds sane and necessary.

What if we did this:

1. Store "viewable" `fileMetadata` fields in configuration (or similar)
2. Inject this config into the [Kahuna client](https://github.com/guardian/grid/blob/f50d816f1d236f0145c1ee84f92a30c721bcab8b/kahuna/app/views/main.scala.html#L40-L47)
3. Provide a new endpoint (or add to existing image endpoint) that makes the selected `fileMetadata` fields available to the client
4. Create `show image metadata` UI component and replace the "show full metadata" component shown on image preview pages. This component will GET from 3.
5. [optional] Allow user to toggle their fields of interest in the UI. Persist their preference in localStorage (similar to panel show/hide configs)

**Comment by ochiengolanga** [comment]
Thanks @akash1810 for the recommendations. I definitely agree that this is a simplified approach by defining and injecting the `fileMetadata` configurations into Kahuna and reuse existing endpoint (can be improved to only serialize visible `fileMetadata` fields in 4 probably from request parameters).

@AWare and @sihil your thoughts on @akash1810 's approach?
