### ISSUE TITLE
Image Collections/Catalogues 

### ISSUE THREAD

**Issue by sihil** [guardian/grid#3192]
Elvis manages collections of images in virtual folders in the system.  These are used to manage catalogues of images and their access policies for different BBC user groups.

Folders/Catalogues are used to manage 2 types of image lifecycle:
1.	Simple lifecycles - Images are assigned to a single catalogue and aren't moved
2.	Complex lifecycles - Images (usually agency images) are moved from an active folder and then either to a deleted folder or an archive folder if archivists want to retain the image for potential future use.  The move between catalogues allows different permissions to be applied to images that are licensed and those that become paid when the license window expires. 
 
Elvis manages collections of images in virtual folders in the system.  These are used to manage catalogues of images and their access policies for different BBC user groups.

We’d like to replicate the functionality of the Elvis folders as image catalogues within the Grid so that:
* Catalogues can be enabled in the Grid
* An image can be assigned to a catalogue as part of the ingest process.
* Catalogue assignment can be done as an ingest pipeline step and can be based on both ingest folders and image metadata.
* An image can only exist in one catalogue at any time
* An image can move between catalogues.
* When manually uploading images users can select a destination catalogue

Use cases for an image's catalogue property are:
* Users can be authorised to edit/delete/crop/use images depending on their user group membership
* Users can be authorised to upload images into catalogues based on their group membership
* Users can filter search results based by applying a catalogue filter
* Kahuna can implement different traffic light styles (when implemented) based on a combination of user group membership and image catalogue properties.

**Comment by sihil** [comment]
One initial question @RichardLe: In Elvis is the same image ever in two catalogues but as two distinct entities in the system? What would you expect to happen if one person uploaded an image into one catalogue and then another person (who perhaps couldn't even see the first catalogue) tried to upload it into a second catalogue without knowing it already existed and they couldn't see it?

**Comment by honorcb** [comment]
Duplicate  "identical" images is an issue in Elvis.  Usually arises  from a freelance photographer working for multiple agencies,  that supply image to BBC,  so same picture gets uploaded with different source and metadata.

**Comment by paperboyo** [comment]
This is currently realised using Collections. Closing for now (although the writeup is useful!).
