### ISSUE TITLE
UX Improvement: Search for images by their additional file metadata on the UI

### ISSUE THREAD

**Issue by Asmau1234** [guardian/grid#3200]
### Short Description

This is a stacked proposal on [Make additional image fields visible on the UI](https://github.com/guardian/grid/issues/3167) proposal which introduces extra image field configuration through this [PR #3183](https://github.com/guardian/grid/pull/3183) that configures additional image fields to be rendered on the Grid Image view UI under the “Show additional metadata” section. 
This proposal leverages the configuration and introduces an approach in which additional search hints can be introduced via configuration to the dropdown search hint / suggestion list on the UI when the user types in **+** into the search bar. Users should be able to select a field, input a value and receive a response with all the results that match the parameters. 

**_Sample configuration:_**
 
>  {
>    elasticsearchPath = "fileMetadata.xmp.bbc:elvis_collection"
>    alias = "bbcElvisCollection"
>    label = "BBC Elvis Collection"
>    displaySearchHint = true
>  }

### Approach

1. Read **fieldAliases** configurations injected into the UI.
2. Filter configurations out so only fieldAlias configurations that have the property `displaySearchHint = true` will have their `alias` in the advanced filter suggestions.
3. Use the elasticSearchPath value to query Elasticsearch e.g  `elasticsearchPath= “fileMetadata.xmp.bbc.elvis_collection” `
4. Serve the user matching results

**Comment by sihil** [comment]
Hi @Asmau1234. I think that we would want these aliases to work when querying the API programatically, not just through the Kahuna web app. As such the aliases need to be mapped on the server side. Possibly this can be done in the `QuerySyntax` or `QueryBuilder` files.

**Comment by paperboyo** [comment]
Closed by https://github.com/guardian/grid/pull/3205. Thanks!
