### ISSUE TITLE
[Accessibility] Add "new image" alert to tab in browser

### ISSUE THREAD

**Issue by ochiengolanga** [guardian/grid#3218]
## Short description

When new images arrive matching the search terms a user has in the search field, a "X new" icon appears and is updated as new images arrive.

This notification is within and only visible from the window that is open or to the fore when a user is looking.

To improve this, the new image notification can be extended and made visible in the tab so a user can see it what focus is on a different tab. When a user has multiple tabs of Grid open, each tab should display this.

## Actual results

![Screenshot at 2021-03-23 17-30-19](https://user-images.githubusercontent.com/12212239/112163088-bf747800-8bfd-11eb-83cf-a406825b3fd4.png)

![Screenshot at 2021-03-23 17-44-25](https://user-images.githubusercontent.com/12212239/112165375-bedce100-8bff-11eb-8be1-2211be52ff83.png)

## Expected results

![Screenshot at 2021-03-23 17-14-30](https://user-images.githubusercontent.com/12212239/112163109-c56a5900-8bfd-11eb-9ebf-faea12124a44.png)

![Screenshot at 2021-03-23 17-43-51](https://user-images.githubusercontent.com/12212239/112165359-bab0c380-8bff-11eb-9aa5-6e3299c6d6b9.png)

## Approach

1. Use AngularJS `$rootScope.$emit` to emit `new-images` event when new images are available after polling
2. Have the `uiTitle` directive react to the `new-images` event using the `$rootScope.$on` and modifying the text in the `<title ...>search | the grid</title>` element to `<title ...>(2 new) search | the grid</title>`.

**Comment by paperboyo** [comment]
I think this is simple and useful: 👍 .
