### ISSUE TITLE
[Accesibility] Navigate to quick filter buttons

### ISSUE THREAD

**Issue by Asmau1234** [guardian/grid#3219]
## Short description

The Quick Filter buttons appear to be not included in the tab order (when a user clicks on the tab key, it skips the “Newest first” and “Oldest first” filters) or accessible to the assistive technology. An improvement is being suggested to make the Grid UI more accessible/user friendly.

## Steps to reproduce

When a user clicks on the tab key, the cursor lands on other buttons on the screen except the quick filter buttons. 

## Actual result

When user hits the tab key, the filters are not selected:

![Screenshot at 2021-03-22 16-17-10](https://user-images.githubusercontent.com/6728165/112168854-f2187380-8bf1-11eb-87b0-499504c75969.png)

## Expected result

When user hits the tab key, the filters are selected:

<img width="159" alt="Screenshot 2021-03-24 at 11 26 07" src="https://user-images.githubusercontent.com/6728165/112295110-debde480-8c93-11eb-9ba8-dcd3e65147df.png">

## Approach

When a user navigates the Grid UI, the quick filter buttons will be included in the tab order or be accessible to the assistive technology by adding a visible highlight to the “Newest first” and “Oldest first” filters. When a user uses the tab index navigation, the cursor would be able to land on these labels.

**Comment by paperboyo** [comment]
Thank you, it’s great to see Grid more keyboard-friendly!

**Comment by paperboyo** [comment]
Fixed by https://github.com/guardian/grid/pull/3223? Closing.
