### ISSUE TITLE
Accessibility: Introduce an edit field to Date Picker

### ISSUE THREAD

**Issue by abdelrahmansd** [guardian/grid#3221]
## Short description
The Date Pickers don't appear to have an edit field to allow users to enter the dates. so it is a little bit hard and unusable to some users.
 An improvement is being suggested to introduce an edit field to allow the user to easily enter the dates

## Actual results

![Screenshot from 2021-03-23 18-20-30](https://user-images.githubusercontent.com/33189781/112274988-c5af3680-8c87-11eb-8ff8-ef4696402f65.png)

## Expected results

![Screenshot from 2021-03-23 19-14-52](https://user-images.githubusercontent.com/33189781/112275048-d6f84300-8c87-11eb-9fce-b87c2aa600d0.png)

## Approach

When the user click on the Date Filter and click on the Filter button
The _From Date_ value will be taken from the _From Edit field_ or fall back to the _From Date Picker_
And also The _To Date value_ will be taken from the _To Edit field_ or fall back to the _To Date Picker_

**Comment by akash1810** [comment]
This is wonderful!

A couple of notes to consider:
- The calendar should sync with the text input
- It might make sense for the "clear" button to live inside/next to the text input
- There are currently three date pickers in the repo (sorry!):
  1. [`<gu-date>`](https://github.com/guardian/grid/blob/b76410e9771e22505967e9d16ed43f1de7aa154f/kahuna/public/js/components/gu-date/gu-date.html)
  2. [`<gu-date-range-x>`](https://github.com/guardian/grid/blob/b76410e9771e22505967e9d16ed43f1de7aa154f/kahuna/public/js/components/gu-date/gu-date-range-x.html)
  3. [`<gu-date-range>`](https://github.com/guardian/grid/blob/b76410e9771e22505967e9d16ed43f1de7aa154f/kahuna/public/js/components/gu-date-range/gu-date-range.html)
  As hinted at in [this PR](https://github.com/guardian/grid/pull/2295) `<gu-date-range-x>` was meant to replace `<gu-date-range>` entirely, however that work wasn't completed for some reason! Ideally we'd finish this first, but I don't think we'd reject a PR that copy pastes these accessibility changes into multiple files.

**Comment by paperboyo** [comment]
Fixed by https://github.com/guardian/grid/pull/3225? Closing.
