### ISSUE TITLE
Feature: Hide/Soft Delete/ Agency images

### ISSUE THREAD

**Issue by abdelrahmansd** [guardian/grid#3314]
## Short description
There is a need to hide images uploaded by agencies once their TTL has expired rather than hard deleting them,
Introduces a way of hiding/soft-delete agencies’ images once their TTL has expired.
This is achieved by adding a deletedAt field on the image model to mark an image is soft-deleted or not

And take this flag into consideration on search endpoint

## Expected results

```scala
case class Image(
 id:                  String,
 uploadTime:          DateTime,
 uploadedBy:          String,
 lastModified:        Option[DateTime],
 identifiers:         Map[String, String],
 uploadInfo:          UploadInfo,
 source:              Asset,
 thumbnail:           Option[Asset],
 optimisedPng:        Option[Asset],
 fileMetadata:        FileMetadata,
 userMetadata:        Option[Edits],
 metadata:            ImageMetadata,
 originalMetadata:    ImageMetadata,
 usageRights:         UsageRights,
 originalUsageRights: UsageRights,
 exports:             List[Crop]       = Nil,
 usages:              List[Usage]      = Nil,
 leases:              LeasesByMedia    = LeasesByMedia.empty,
 collections:         List[Collection] = Nil,
 syndicationRights:   Option[SyndicationRights] = None,
 userMetadataLastModified: Option[DateTime] = None 

 // new field 
 deletedAt: Option[DateTime] = None,
)
```

## Approach
When an image is created, the _deletedAt_ field will be set to _None_ by default.
in the UI, there will be a new search filter called _isDeleted_ which will be a boolean flag to specify whether to get deleted images or not, by checking if the _deletedAt_ field exists or not.
this flag will be set to false by default in case the user doesn't have proper permission to view soft-deleted images

Once an agency image TTL has expired the _deletedAt_ set to _Now_, this will be done by BBC Specific implementation (Lambda function)

Normal users should not be able to see the hidden/soft-deleted images
When a user has proper permission he can set the search filter isDeleted to true
Then the user should be able to see all the hidden/soft-deleted images

**Comment by AWare** [comment]
We've been looking at some UX around doing similar with out of quota images, and this sounds like it could be relevant. Might be worth discussing at the next weekly meeting.

**Comment by sihil** [comment]
I think something like this makes a lot of sense. 

A few initial questions to help flesh out the idea:
 - In which canonical data store will this new field be stored?
   - Depending on the answer to this the field might be better in a sub object rather than at the top level.
 - Is it expected that the field can be set to a date in the future and if so what behaviours are expected when this is the case?
 - Do you expect a user that has permission to _view_ these images to be able to _use_ them (i.e. crop and/or download the image)?
 - Does the TTL also live in the data model somewhere or does that come from a usage right or something else?

**Comment by paperboyo** [comment]
Another question to consider:
- should a permissioned users be able to undelete a picture (eg. by Adding to Library)?
- is “delete” a good term? it describes a state distinctly different from current “delete” in the UI. I’m bad with names but eg. “expired” comes to mind?

**Comment by abdelrahmansd** [comment]
> In which canonical data store will this new field be stored?

it will be in the image model in elasticsearch. i believe it will be better to be in the top level , because it doesn't belong to any sub object

> Is it expected that the field can be set to a date in the future and if so what behaviours are expected when this is the case?

no, it will be set once the image marked as hidden/soft-deleted. 

>Do you expect a user that has permission to view these images to be able to use them (i.e. crop and/or download the image)?

the user who has the right permission can undelete (Add to Library) image then he can use it.

>Does the TTL also live in the data model somewhere or does that come from a usage right or something else?

it is a BBC configuration, this will be done by BBC Specific implementation (Lambda function)

>should a permissioned users be able to undelete a picture (eg. by Adding to Library)?

the user who has the right permission can undelete (Add to Library) image.

>is “delete” a good term? it describes a state distinctly different from current “delete” in the UI. I’m bad with names but eg. “expired” comes to mind?

agree with you, we can use a better term like "hide"

**Comment by abdelrahmansd** [comment]
> In which canonical data store will this new field be stored?
also, it might be in the Edits model in userMetadata

**Comment by akash1810** [comment]
> > Is it expected that the field can be set to a date in the future and if so what behaviours are expected when this is the case?
>
> no, it will be set once the image marked as hidden/soft-deleted.

Being able to set dates in the future would be massively helpful, I think. Some of our agency feeds are made available for specific time frames. For example, Getty images are available for 2 months (I don't know the exact details of our contract!).

Being able to set the value of `deletedAt` on image upload makes the clean up process super simple - a lambda that deletes all images where `deletedAt` is before `Date.now()`.

Is the plan for "soft delete" to replace the current image deletion feature, where an image is deleted immediately? I would suggest it should, for simplicity. We'd swap "delete this image now" to "set `deletedAt` to `Date.now()` and wait for the lambda to run".

**Comment by abdelrahmansd** [comment]
@akash1810 the initial plan is to hide/soft-delete images with  expired TTL from normal users
and authorized users can filter images by status of hidden and add them to library
however, I agree with your suggestion

**Comment by paperboyo** [comment]
Just today, this feature would have saved our ass… Which got me thinking: a lot of actions in Grid have an author added to them in the API, so it’s possible to seachr by eg. `leasedBy`, `author` of a crop (using an alias chip `cropppedBy`).

Do you think `deletedAt` should have its `deletedBy` too? Would record emails, but also any robots. Would allow to see images deleted by real users by excluding `-deletedBy:[robot name]` and to see images deleted by yourself, etc.

What do you think?

**Comment by paperboyo** [comment]
In production now.
