### ISSUE TITLE
Consistant, more attractive & useful error handling

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#366]
Arguable `$window.alert()` is consistant, but doesn't allow for adding anything useful e.g. a redo button on fail.

[`ngMessages`](https://docs.angularjs.org/api/ngMessages/directive/ngMessages) might be a solution.

**Comment by NickPapacostas** [comment]
https://github.com/guardian/grid/commit/ee84c2e3be299bdfcaeda782a55511252010565a

@jamesgorrie assuming I can close this, let me know if i'm being hasty :)
