### ISSUE TITLE
Shared URLs do not affect app state correctly

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#3780]
We are receiving user reports that possibly recent work (probably https://github.com/guardian/grid/pull/3645 and https://github.com/guardian/grid/pull/3724?) results in incorrect/confusing behaviour.

### Scenario 1

1. set `show_paid` permission to `true`
2. clear search and check Free to use checkbox
3. navigate to the URL with `&nonFree=true` that includes paid imagery (eg. https://media.gutools.co.uk/search?query=category:chargeable&nonFree=true)

Actual result:
`&nonFree=true` disappears from the URL and the sent search contents is not reflected

Expected result:
The sent URL should override app state.

### Scenario 2

1. set `show_paid` permission to `false`
2. clear search and navigate to the URL with `&nonFree=true` that includes paid imagery (eg. https://media.gutools.co.uk/search?query=category:chargeable&nonFree=true)

Actual result:
`&nonFree=true` disappears from the URL and the sent search contents is not reflected

Expected result:
The sent URL should override app state. Users are often sharing URLs and the receiver is expected to see the exact same results as the sender not dependent on their permissions or app state.

### Scenario 3

1. irrespective `show_paid` permission state (sic!)
2. (if `show_paid` is `false`) uncheck Free to use checkbox
3. navigate to a paid for image
4. click any of the outgoing search links eg. underline byline

Actual result:
Free to use checkbox appears unchecked, **but** (incorrectly), URL looses `&nonFree=true`, so the very image from which the search started is not included in results. 

Expected result:
The search URL should include the current app state. 

5. reload the page

Actual result:
It “fixes itself” after reloading the page.

Expected result:
There should be no mismatch between app state and URL that is cleared on page reload.

**Comment by andrew-nowak** [comment]
this is an example of how we could fix scenario 3 (there may be better methods, it's worth exploring further) https://github.com/guardian/grid/commit/78982025c2de41419e8cca8df04994ac21a5e03f
