### ISSUE TITLE
new image-loader architecture

### ISSUE THREAD

**Issue by andrew-nowak** [guardian/grid#4026]
## Short description

we have a couple of problems with image-loader: the biggest and most frequent is when a user uploads several large (often TIFF) images. because image-loader loads files *synchronously*, it attempts to load all images into memory at the same time (can cause out-of-memory-issues) and then run imaging operations (crops, resizes, etc.) at the same time (cpu exhaustion). the only solution is to scale up, but this is very wasteful for the 99% of time where there is not a batch of big images being uploaded (scaling after the upload *doesn't help* because the requests have already been allocated to instances, so those instances still need to struggle through (which they often can't))

instead, we should load files *asynchronously* --- ie. user uploading a file into the UI means the file will be processed in the near future, not necessarily immediately. this then frees up image-loader to be scrupulous about how much working it performs in parallel and only start processing an image when it is ready.

## current architecture

```mermaid
flowchart LR
  user(User)
  ftp(FTP server)
  image-loader(image-loader\nec2)
  ingest[(ingest bucket\ns3)]
  s3watcher(s3watcher\nlambda)
  bucket[(image bucket\ns3)]
  elastic[(elasticsearch)]
  status[(upload status\ndynamo)]

  user -- 1 --> image-loader
  ftp -- 2 --> ingest
  ingest -- 3 --> s3watcher
  s3watcher -- 4 --> image-loader
  image-loader -- 5 --> bucket
  image-loader -- 5 --> elastic
  image-loader -. 6 .-> status
```

1. User makes an "upload" request to image-loader, image bytes are sent in the payload (or an "import" request, in which case this is more similar to 4, where no image bytes in request payload, instead a url of an image to fetch).
2. FTP service(s) upload files into the s3 watcher ingest bucket
3. S3 watcher is invoked with an [s3 event notification](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html)
4. S3 watcher sends an "import" request, with url to image in s3 watcher ingest bucket
5. Image-Loader processes "upload" or "import" requests (in upload, saves incoming bytes to file, then processes; in import, fetches image from url, save to file, then processes as in upload), sends image file to image bucket and saves image model to elasticsearch
6. Users of the quarantine lambda also have status written to status bucket, and uploads go through the quarantine lambda before 5

## proposal

```mermaid
flowchart LR
  user-upload(User upload)
  user-import(User import)
  ftp(FTP server)
  queue{{upload queue\nsqs or kinesis}}
  image-loader(image-loader\nec2)
  ingest[(ingest bucket\ns3)]
  s3watcher(s3watcher\nlambda)
  bucket[(image bucket\ns3)]
  elastic[(elasticsearch)]
  status[(upload status\ndynamo)]

  %% hidden links to influence node positioning
  queue --- status
  queue --- bucket
  queue --- elastic
  linkStyle 0 stroke:#fff0,color:#fff0
  linkStyle 1 stroke:#fff0,color:#fff0
  linkStyle 2 stroke:#fff0,color:#fff0
  %% end of hidden links

  user-upload -- 1 --> image-loader
  user-import -- 5 --> image-loader
  ftp -- 2 --> ingest
  user-upload -- 2 --> ingest
  ingest -- 3 --> s3watcher
  s3watcher -- 4 --> queue
  queue -- 6 --> image-loader
  image-loader -- 7 --> bucket
  image-loader -- 7 --> elastic
  image-loader -- 1, 6, 7 --> status
  s3watcher -- 4 --> status
  image-loader -- 5 --> queue
  
```

1. User sends an upload request to image-loader, _not including image bytes_. Image-loader responds with an [S3 presigned url](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html). "uploading" status written to status table
2. User or FTP server uploads to ingest bucket (user uses presigned URL, FTP server uses normal IAM permissions)
3. S3 watcher is invoked with an [s3 event notification](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html)
4. S3 watcher places a message on the ingest queue for the image with s3 url for the image. "queued" status written to status table
5. User sends an import request to image-loader, which directly places a corresponding message on the ingest queue.
7. Image-loader, when it has free capacity, takes a message off the queue, downloads the image from the url in the message (s3 or web) and processes (ie. same as a current "import" request). "processing" status written to status table
8. Image-loader processes downloaded image, sends image file to image bucket and saves image model to elasticsearch. "complete" or "failed" status written to status table

## remaining

- some deployments use the quarantine lambda to check the image for malicious payloads before fully processing. we need to figure out how to integrate it - I'm pretty sure it could go in front of s3 watcher but I've not thought too hard about it. 
- upload status table isn't technically necessary for the above described - but we can use the values in the frontend to provide fairly helpful feedback to users watching their uploads (since they _could_ be slower than before, eg. if there's _huge_ amounts of small images ahead, which are clogging up the image-loader instances)
- having messages on a queue is great, because we could feasibly set up auto scaling alarms based on queue depth - eg. if there's several hundred items waiting on the queue, add a new instance to process them, then when we're back under 5, scale back down

**Comment by andrew-nowak** [comment]
> replacing s3 watcher with the SQS queue

sounds like a great simplification! very very nice

> A1. User does POST request to image-loader (same as currently)
> A2. image-loader uploads to ingest bucket for user

I can't tell if you have already from your post, but I'd really really recommend trying [S3 presigned urls](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html) - if they work (and I think they should) the image bytes can go directly to s3, without going via image-loader first. That way there's no worries about users trying to upload large batches of large images in one go, possibly exhausting memory, because it's entirely s3's problem. the only thing image-loader has to do is ask for a presigned url which will be much much cheaper

**Comment by twrichards** [comment]
BBC's Quarantine Related:

- https://github.com/guardian/grid/issues/3123
- https://github.com/guardian/grid/pull/3082
- https://github.com/guardian/grid/pull/3126

**Comment by twrichards** [comment]
This has been done mainly in https://github.com/guardian/grid/pull/4201 (plus various follow-up PRs)
