### ISSUE TITLE
rethink metadata-editor name

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#409]
The problem being labels and archive are not metadata and we now have metadata within the root metadata.

At the moment the structure is something like:

```
metadata(root)
├── archive
├── labels
└── metadata
```

Perhaps something catchy like `info-overrides` or perhaps just `override` ([which isn't as banal as you might think](http://tfwiki.net/wiki/Override_%28Cybertron%29)) or in the vain of `cropper` and `reaper` perhaps `usurper` or `superseder`.

**Comment by akash1810** [comment]
I think we're too far down this road now to turn back!

Closing.
