### ISSUE TITLE
"(Credit too long, see caption)" as Getty credit

### ISSUE THREAD

**Issue by theefer** [guardian/grid#532]
Getty sometimes helpfully provides `(Credit too long, see caption)` as credit string. There are 1483 occurrences in PROD as this time (search for `credit:"(Credit too long, see caption)"`).

We could harvest the credit out of the caption in that case, e.g.

`DOHA, QATAR - MARCH 11: Palme dOr winning director and producer Cristian Mungiu at a portrait session during the inaugural edition of Qumra, a new industry event by the Doha Film Institute dedicated to the development of emerging filmmakers on March 11, 2015 in Doha, Qatar. (Photo by Ian Gavan/Getty Images for Doha Film Institute)`

**Comment by paperboyo** [comment]
4,534 as of today. For a list of some ideas about better cleaners, see [this doc](https://docs.google.com/spreadsheets/d/17ad1AOurfYO_dWTZuy6EWfjqeH7-Q_f0WlYrojJMzow/edit#gid=1688930411) and [comments](https://github.com/guardian/grid/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/cleanup/SupplierProcessors.scala#L267) in cleaners code.

**Comment by paperboyo** [comment]
Fixed by https://github.com/guardian/grid/pull/2344.
