### ISSUE TITLE
[UI] Apply to all on FF a little off

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#640]
As per @paperboyo's catch

![](https://cloud.githubusercontent.com/assets/6032869/7161956/e10ecef2-e389-11e4-872d-59cb9dc52251.jpg)

**Comment by akash1810** [comment]
FYI frame handle has been removed in https://github.com/guardian/grid/pull/662.

**Comment by paperboyo** [comment]
Thanks, @akash1810! Original (super-minor) issue still there.

**Comment by jamesgorrie** [comment]
Doesn't seem to be there now.
