### ISSUE TITLE
Let Dynamo lib accept case classes

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#642]
We've done something that's moving in that direction [here](https://github.com/guardian/media-service/pull/641#discussion-diff-28440405R211).

We now need to do what the TODO says and move it [here](https://github.com/guardian/media-service/blob/master/common-lib/src/main/scala/com/gu/mediaservice/lib/aws/DynamoDB.scala#L123)

**Comment by kenoir** [comment]
This work is available in https://github.com/guardian/scanamo
