### ISSUE TITLE
UI bugs causing media-api request spam

### ISSUE THREAD

**Issue by theefer** [guardian/grid#712]
There seem to be one or several bugs in kahuna that cause clients to issue many requests to the API.

Suspects include:
* Failed uploads (or succeeded after client timeout), causing endless polling
* Session expiration

They can typically be seen on the graphs and in the api logs (request logging).

This doesn't seem to affect the media-api performance but it'd be good to get to the bottom of it to avoid noise on graphs.

**Comment by theefer** [comment]
Not seen in a while?

**Comment by jamesgorrie** [comment]
This can probably be lumped into finding a new solution to polling soheavily.
