### ISSUE TITLE
Clients requesting unbundled assets from kahuna

### ISSUE THREAD

**Issue by theefer** [guardian/grid#713]
Some of the spikes on kahuna graphs seem to be the result of one or more clients requesting all the unbundled assets from kahuna (rather than the single bundle.js file). The individual files are typically requested many times over in small succession (see request log).

I can't think of why a client would not resolve all these files to the bundle, so it's a mystery. Another hypothetical culprit could possibly be Sentry, downloading sources to resolve sourcemaps?

**Comment by akash1810** [comment]
I think this no longer happens. Closing.
