### ISSUE TITLE
Store client errors somewhere

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#719]
We need a place to store program errors such as:
- Upload fail
- Edits fail
- Query fail

Sentry seems like a no go area as that should be reporting client code errors.
Mixpanel can't alert, and the graphs aren't easily embeddable, so it seems a little shit too.

Logstash seems like a natural place perhaps?

**Comment by paperboyo** [comment]
We are logging these now, I think. Safe to close, I believe.
