### ISSUE TITLE
Review out-of-order handling of message queue

### ISSUE THREAD

**Issue by theefer** [guardian/grid#785]
I'm not sure we reliably handle the fact that messages pulled from SQS may not come or be processed in the order they were created.

For example, if two crops are created in quick succession, there may be a race condition which would result in the latest entry in `exports` not getting indexed, depending on the processing order. We should review this and if necessary, introduce better logic (based on time or predictable sequences) to cope with such situations.

**Comment by kenoir** [comment]
Done thanks to @NickPapacostas
