### ISSUE TITLE
Add all categories to `usageRights`

### ISSUE THREAD

**Issue by jamesgorrie** [guardian/grid#787]
- [x] Subscription agency
- [x] Staff photographer
- [x] Contracted photographer
- [x] Commissioned photographer
- [x] Social media news image
- [x] Guardian Witness
- [x] Handout
- [x] Screengrab
- [x] Supplied for obituary
- [x] Pool / Rota
- [x] PR Image

**Comment by akash1810** [comment]
Looks complete.
