### ISSUE TITLE
Add Batch download

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#830]
Hello,

Tell me if feature requests don't belong here, I try to put here only the obvious ones, but hey - you know me :)

Downloading more than one image is currently a pain. Even more so in Firefox which does not support our downloading mechanism properly (opens an image in a new tab from where one has to Save the image as...).

An ability to download multiple selected photos would be cool. Most probably they would have to be zipped (stored), would be even better if they wouldn't (user would just have to specify a destination folder).

Regards
Mateusz

**Comment by alastairjardine** [comment]
UI perspective: selection would enable this button on the new fixed toolbar.

**Comment by paperboyo** [comment]
Done in https://github.com/guardian/grid/pull/1080. Thanks. Some very minor things to fix (or not) in https://github.com/guardian/grid/issues/1123#issuecomment-133298077.
