### ISSUE TITLE
"Reuters" becomes "REUTERS" on any user interaction

### ISSUE THREAD

**Issue by paperboyo** [guardian/grid#971]
Hello,

Ok, I don't know if "any", but:

1. Run https://media.gutools.co.uk/search?query=credit:Reuters
2. Add a label or archive image
3. Credit for that image becomes "REUTERS", so that it will disappear from the above search on refresh

Not a massive thing, just slightly annoying and triggers a lot of manual editing or wrong credit on live site. Also, baffling as to why it happens in the first place... :smile:

Regards
Mateusz

**Comment by akash1810** [comment]
I can tell you what it ISN'T... Its not to do with ignoring casing of metadata fields when POSTing a label. Why? Because the label endpoint is different from the metadata endpoint!

**Comment by theefer** [comment]
Is this still happening?

**Comment by paperboyo** [comment]
Yep. Just tried on 9310b9b37cbc640f2ca8e8223712187ba87777c5...

**Comment by theefer** [comment]
This is quite odd. Going to take a look...

**Comment by paperboyo** [comment]
Thx, @theefer!

**Comment by theefer** [comment]
@paperboyo thanks, that was actually caused by an annoying bug.
