### ISSUE TITLE
Usage rights should appear inline rather than behind dropdown.

### ISSUE THREAD

**Issue by kenoir** [guardian/grid#991]
![usage_rights_jpeg](https://cloud.githubusercontent.com/assets/953792/8930085/9059d1a6-3522-11e5-91d3-d64ba097db10.jpg)

**Problem:** 

The usage rights are hidden behind a button resulting in an extra click to edit. This occurs on all pages the usage-rights control appears.

**Solution:**

Inline the usage-rights control

/cc @alastairjardine

**Comment by theefer** [comment]
Seems like this could be a step toward unifying the layout of metadata between search/preview and uploads?

Not sure yet that they need to be exactly the same, as they serve a slightly different function, but would be nice to preview the detected category on the uploads page the same way we do on the search/preview panel.

**Comment by theefer** [comment]
This is done.
