### ISSUE TITLE
Replace tick and cross with save/cancel text when saving fields

### ISSUE THREAD

**Issue by kenoir** [guardian/grid#992]
![tc_jpeg](https://cloud.githubusercontent.com/assets/953792/8930158/5c633e54-3523-11e5-9116-4c448238cc0f.jpg)

**Problem:** 
The tick and cross controls when saving data to a field are not explicit enough in their intention.

**Solution:**
Add more explicit text "save/cancel"

/cc @alastairjardine

**Comment by theefer** [comment]
I thought that we used these on purpose to unify with Workflow, but I don't mind actions being more explicit.

**Comment by alastairjardine** [comment]
@theefer We're lucky here because of the placement – workflow needs to accommodate even smaller spaces, hence the simplified button styling there.

**Comment by theefer** [comment]
@alastairjardine :+1:
