### ISSUE TITLE
Responsive search results

### ISSUE THREAD

**Issue by kenoir** [guardian/grid#994]
![results_jpeg](https://cloud.githubusercontent.com/assets/953792/8930390/7526ec7c-3525-11e5-8468-ee178e24a1ea.jpg)

**Problem:** 
At smaller widths very few images are displayed per row in the search results.

**Solution:**
Allow search results to respond to width by allowing more results per row with less spacing and contextual information at smaller widths

/cc @alastairjardine

**Comment by alastairjardine** [comment]
Lots of opportunity to improve the usability in this space. 

We should think about/consider
* context and task e.g. if you've inputted a search term, the context is obvious, therefore do you need the beginning of a description? How useful is full date on a small screen? 
* methods to chimp (applicable to all sizes, actually)
* usability of side panels

**Comment by theefer** [comment]
> How useful is full date on a small screen?

Date information is one of the most crucial pieces of information according to several independent users (they sometimes get it wrong and it's a big deal), in terms of making sure this is the picture you think it is (i.e. the trial/football match/awards on that date). However it's likely we could emphasise different part of the information based on age, e.g. clear time for today/yesterday, but focus on date past a certain age.

**Comment by paperboyo** [comment]
Being better on mobile requires wider rewrite of the UI. Closing for now.
